In [57]:
# Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. 
#     You have to scrape the job-title, job-location, company_name, experience_required. 
#     You have to scrape first 10 jobs data.

In [96]:
import pandas as pd
import selenium
from selenium import webdriver

In [97]:
driver=webdriver.Edge("msedgedriver.exe")

In [98]:
url= "https://www.naukri.com/"
driver.get(url)

In [99]:
#finding element for job search bar
search_job=driver.find_element_by_id("qsb-keyword-sugg")

In [100]:
# writing on search bar
search_job.send_keys("Data Analyst")

In [101]:
#finding element for job location bar
search_loc=driver.find_element_by_id("qsb-location-sugg")

In [102]:
# writing on search bar
search_loc.send_keys("Bangalore")

In [103]:
#do click using xpath function
search_btn=driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [66]:
#Now we will see in the window opened by webdriver whether the webpage has opened or not.Lets check it.
#Now first craete 4 empty list.In this list we will store data which will be scrapped.
#We have craeted 4 empty lists for 4 features which we have to extract
#job title ,company names ,locations_list,experience_list

In [104]:
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title_tags

[<selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="e0e2cdc5-833b-4fff-9613-086e9e358c43")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="fe70e82b-53bb-4145-8c86-fd274b466943")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="d947fb7e-ba22-413c-8366-eaa70079fa45")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="98474424-fbc7-4a2f-8fcf-7a634c056924")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="c6676a92-00d4-4c77-863d-c4c6f0c9221c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="07a88a9a-ab0c-4f79-ae37-f0ca69bd3673")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="67cb5518-e06e-4a4e-9863-be6808d6fbd9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="f9c36c03-d210-4142-9884-2914fcc1716f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="acb6c1dd-81dc-4eb9-9f15-58cdf27114f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="2e3b795e-93b7-49e9-81f7-ed3e17c3a02f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="60670459-85cd-4827-bf79-03c2452d97ce")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="04bce8b0-005e-46f4-b0e5-9fd63cd3ccc5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="225087f6-e79a-4efc-9d74-1db534b97c93")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="1e81ff11-f539-492f-bdfc-fed687a21fea")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="a23dfb32-7cf2-466d-9b42-2ddd1ba28a0d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="b0145406-253c-4753-be40-5d0e8b81e1db")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="3e941b7b-8025-4d91-bb67-09e975d5c458")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="1b966323-35fe-4ea6-93e4-7ef388ab8df3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="367d3584-9a32-470a-ac1c-32c4d3c9b9e0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="88ddc919-379a-4d8e-a4d6-81bcfd8310c5")>]

In [105]:
#now we will extarct text from web element
job_titles=[]
for i in title_tags:
    job_titles.append(i.text)
job_titles

['Data Scientist / Data Analyst -Business Analyst',
 'Data Analyst - Informatica MDM',
 'Assistant Vice President - MIS & Reporting ( Business Data Analyst)',
 'Data Analyst',
 'Hiring For Data Analyst/ MIS Reporting Analyst - Bangalore',
 'Consultant-Data Analyst -Bangalore',
 'Data analyst - Google Analytics',
 'Senior/Regular Business Analyst / Data Analyst',
 'SW Technologist I- Data Analyst',
 'Data Analyst',
 'Hiring For Data Analyst @ Flipkart on Contract',
 'Data Analyst - Informatica MDM',
 'Senior Data Analyst',
 'Cybersecurity Data Analyst',
 'Data Analyst / Business Analyst -',
 'Business Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst']

In [106]:
companies_tag=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tag

[<selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="8ccc17f1-e8a8-4a80-bf8b-91f5ef5cbaa8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="76570bd3-55e8-4784-9a2d-660cdf03c43e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="a54f50a2-fb35-41e2-9494-24ebd2e5d706")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="dfae37de-5126-436a-8402-950eb27d5ade")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="67272959-0d97-402f-9099-885b9169ba01")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="313fd1dd-2a1e-4021-94e2-98ceb25be288")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="82784848-1c57-4832-98f8-073684e87595")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="1612cfe7-f4f7-448e-92c7-917d98d7bf13")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="c1ea3032-e384-423a-a17b-d8239a00f3d1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="a8a5f0ef-8428-43d2-9741-4148a4fbfbef")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="01458456-6396-4a82-b644-392e6a1ce2eb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="9653a512-e9ef-4f4a-8b06-4038290c8a84")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="c1e2995c-ad86-4cb8-9e3d-c3048214bdd8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="2f3b93ed-febb-495d-b32b-8acbc9cf58f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="dac344e6-6b78-4150-9d54-8123e2c1e054")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="463a6182-2e1f-493b-bbe4-db0e3d47f9a4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="ee35ebe0-88dc-4d02-b85e-ba80d8b01830")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="e796c49f-c079-4abc-bb05-323bd9938875")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="28e26ecb-7ef5-4b92-8bec-a4d80e4dee51")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="457e35ca-33fd-4598-a26a-8632b51f5c21")>]

In [107]:
company_names=[]
for i in companies_tag:
    company_names.append(i.text)
company_names

['Inflexion Analytix Private Limited',
 'Shell India Markets Private Limited',
 'INTERTRUSTVITEOS CORPORATE AND FUND SERVICES PVT. LTD.',
 'SA Tech Software (I) Pvt. Ltd.',
 'PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd',
 'Innovsource Services Private Limited',
 'H and M Hennes and Mauritz (P) Ltd.',
 'Luxoft',
 'Philips India Limited',
 'Flipkart Internet Private Limited',
 'Flipkart Internet Private Limited',
 'Shell India Markets Private Limited',
 'Flipkart Internet Private Limited',
 'Huawei Technologies India Pvt Ltd',
 'LatentView Analytics Private Limited',
 'ALSTOM India Limited',
 'Udaan',
 'Luxoft',
 'Yodlee Infotech Private Limited',
 'Novel Office']

In [108]:
##here li is the parent tag and span is the tag containing the data therefore used at end
#Also we can span[1] or span[2] if two span tag present..
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location_tags

[<selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="90ef7b24-c5e6-4ddc-93fb-f5c81cac12f4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="b1ca291d-ac77-4d26-8a89-9252e4c5319f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="33a831a5-8689-4c6a-98e3-304c1e1cccf0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="8bbfec55-82f6-4df9-b788-a9052b91a26a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="c992b9ed-cf42-4e4d-9f3f-9ec8df2eb55a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="844fa532-4c27-4434-820a-d9f876f7e172")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="03ae35b8-f7f1-448d-8eb9-eb114011da62")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="a2711004-1179-4379-8e5b-e2797278341a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="c745e896-36b6-4c14-b639-7c2793475eec")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="34ac91d3-3873-49c7-a9ce-5d56ed640762")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="ff9a4442-d978-4ded-947e-4c206b8a3611")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="03c0e42c-4e29-4c20-a2b3-c5fb104a5c0b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="69dd7a4c-342b-467a-9ed4-e74701c6254e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="ed16c3d8-e4c1-409b-bd87-c97dddf51e43")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="89644843-137d-4d5a-a318-7313d71d1b53")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="6eafb186-32ba-4516-8a8f-87fd52febb4a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="ea631c84-5828-4869-a974-d0e4ff0670b6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="e87ace95-619f-4e3f-8cf2-f55145799b75")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="cf4ef904-1d90-4452-ba43-c9eff5763dad")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="3730013c-a129-4375-b944-005c5be13c60")>]

In [109]:
location_list=[]
for i in location_tags:
    location_list.append(i.text)
location_list

['Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Bangalore/Bengaluru',
 'Kolkata, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [110]:
##here li is the parent tag and span is the tag containing the data therefore used at end
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span")
experience_tags

[<selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="78f958b1-c4b0-4b0e-a3e8-2efeea22da84")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="19536da4-394e-4ca5-8546-8de4f33b0f41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="ecb9b35b-3e15-449c-8760-aec6053b643b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="65ffe288-11a4-4132-bbe2-c6f5143acb18")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="be9a1b0a-89f8-4dd4-a24b-8bcba175cdbb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="1549b7e9-c43a-453e-aac6-35b5c3712605")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="ebfbc4fb-5093-46b0-8601-b14d7bbcdf0b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="466dc654-7adc-45c3-9ffb-c6cb12162ce0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="d41d0498-3311-4942-80ea-f142c8b5eba1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="473eb281-a7c0-4fea-9473-dd489baa0ac5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="2e4b5b98-cce9-41bc-8a6d-3b5043a9ac9e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="c3419d82-e18f-472f-a94f-c7be355d0c1c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="54121cdd-ded0-43a8-b152-942434320cf7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="4d5b717f-4be1-4c5e-922a-bee20fee6b34")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="26180e40-400f-42e4-93f7-58f7f3912db2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="a7be96df-a2ec-476b-9981-fdf2127a26ec")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="d7e9df99-237d-4d3b-9c30-f6fe50df3dab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="73a8e9e2-37cc-45b3-83dd-0725f7dece48")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="da5287d3-daa9-4c27-950f-53a4700d221f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="60a78b545b8bf8053a570e1d8ec79f09", element="7c870493-9be9-4c88-861e-79414b629638")>]

In [111]:
experience_list=[]
for i in experience_tags:
    experience_list.append(i.text)
experience_list

['0-3 Yrs',
 '6-9 Yrs',
 '12-18 Yrs',
 '1-3 Yrs',
 '2-4 Yrs',
 '2-7 Yrs',
 '4-7 Yrs',
 '3-6 Yrs',
 '5-10 Yrs',
 '1-3 Yrs',
 '2-6 Yrs',
 '6-9 Yrs',
 '2-5 Yrs',
 '5-8 Yrs',
 '1-5 Yrs',
 '5-10 Yrs',
 '1-6 Yrs',
 '2-6 Yrs',
 '2-6 Yrs',
 '0-3 Yrs']

In [112]:
jobs=pd.DataFrame()
jobs["title"]=job_titles[:10]
jobs["company"]=company_names[:10]
jobs["experience_required"]=experience_list[:10]
jobs["location"]=location_list[:10]

In [113]:
jobs

,title,company,experience_required,location
0,Data Scientist / Data Analyst -Business Analyst,Inflexion Analytix Private Limited,0-3 Yrs,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/..."
1,Data Analyst - Informatica MDM,Shell India Markets Private Limited,6-9 Yrs,Bangalore/Bengaluru
2,Assistant Vice President - MIS & Reporting ( B...,INTERTRUSTVITEOS CORPORATE AND FUND SERVICES P...,12-18 Yrs,"Mumbai, Bangalore/Bengaluru"
3,Data Analyst,SA Tech Software (I) Pvt. Ltd.,1-3 Yrs,"Kolkata, Pune, Chennai, Bangalore/Bengaluru, D..."
4,Hiring For Data Analyst/ MIS Reporting Analyst...,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4 Yrs,Bangalore/Bengaluru
5,Consultant-Data Analyst -Bangalore,Innovsource Services Private Limited,2-7 Yrs,Bangalore/Bengaluru
6,Data analyst - Google Analytics,H and M Hennes and Mauritz (P) Ltd.,4-7 Yrs,Bangalore/Bengaluru
7,Senior/Regular Business Analyst / Data Analyst,Luxoft,3-6 Yrs,Bangalore/Bengaluru
8,SW Technologist I- Data Analyst,Philips India Limited,5-10 Yrs,Bangalore/Bengaluru
9,Data Analyst,Flipkart Internet Private Limited,1-3 Yrs,Bangalore/Bengaluru

In [77]:
#Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. 
#    You have to scrape the job-title, job-location, company_name, full job-description. 
#    You have to scrape first 10 jobs data.

In [131]:

driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.naukri.com/"
driver.get(url)

In [132]:
#finding element for job search bar
search_job=driver.find_element_by_id("qsb-keyword-sugg")

In [133]:
# writing on search bar
search_job.send_keys("Data Scientist")

In [135]:
#finding element for job location bar
search_loc=driver.find_element_by_id("qsb-location-sugg")

In [136]:
# writing on search bar
search_loc.send_keys("Bangalore")

In [137]:
#do click using xpath function
search_btn=driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [84]:
#Now we will see in the window opened by webdriver whether the webpage has opened or not.Lets check it.
#Now first craete 4 empty list.In this list we will store data which will be scrapped.
#We have craeted 4 empty lists for 4 features which we have to extract
#job title ,company names ,locations_list,job_description

In [138]:
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title_tags

[<selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="576793b4-f302-443f-addc-7347b712c52b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="620bebfe-d253-4d46-874d-4106538d4993")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="c8ef40ec-0806-4f5b-ab2a-a5879f83d4a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="53db6bee-7193-4a49-8939-9a0733cbac4d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="4a49c907-76bc-4808-b896-1d271e76369f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="e200be7d-8805-42d5-9cd7-58db05c1316d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="7505c878-6064-4487-8e11-70e7695ee948")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="d226a4a8-f5a2-4de8-83f3-b035cd54af9a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="f1591b56-6952-4d79-b05b-1a3e786e0dc5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="5bc6a6fc-61f2-491b-b975-251c479ed647")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="7121ddcd-a54e-40a8-a31e-b0442808b519")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="bdb4d420-5f75-4441-b45e-f7952671627c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="7f35bd6e-64a7-4fb8-8c67-336faa85a86e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="967aca61-4ca7-47b3-a095-06601d7864bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="886dffe0-f719-4dd4-be9d-56d6499ecae6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="b1a55e87-aa74-4e90-aa18-6bfa0081473b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="bb973b37-cc84-4066-adbd-b5929bf1e836")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="8350b88d-eb5c-48be-82bb-76e0315b3ab9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="672208ae-39a5-4172-94d3-1372e0ee9f61")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="47875c12-770a-4f9e-8834-7777f531f234")>]

In [139]:
#now we will extarct text from web element
job_titles=[]
for i in title_tags:
    job_titles.append(i.text)
job_titles

['Data Scientist',
 'Data Scientist',
 'Data Scientist - Python/ SQL',
 'Data Scientist - Machine Learning',
 'Data Scientist - Python/r',
 'Data scientist - Bangalore - only IITand IIM',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist - Optimus ( RL/ DL)',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Lead Data Scientist']

In [140]:
companies_tag=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tag

[<selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="5ba00fc8-3885-4f43-82dc-181499dcbb98")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="99f155d5-24c6-4a11-9a8e-d3b179c203ee")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="aeec1c46-cb01-4342-83b9-6eb99f998af3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="1c152d62-254b-4dd2-8bf2-a1241f5d120e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="8688b23b-a316-4f54-b1ba-1926173007c9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="d7f38004-f7d6-420a-99b3-69805fcfcff6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="bf122895-ea30-43f5-b94f-a25c06bfbebe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="b2fadb4d-e5b2-47e4-95fc-0716934c2dcc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="3e25a11a-dc78-4025-afa3-39a75d5e9cc8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="d00c132c-8dd9-4b06-81b2-e06e7f2cae64")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="af4c9427-04c3-416a-b2e5-074386bf2971")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="01b3f9d6-f46a-4899-9fe8-f4bb6db6d1c7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="3300e6e3-f019-42d5-8bbb-b9a4ecf98e81")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="5a810194-b1f6-434e-a457-917d35430a3d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="aa88737c-4a48-4302-b041-ab43083cb06b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="23db05af-aa31-4af3-8539-dde5cb0c91be")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="fd9e2bea-cdfd-488a-8dd8-656399732c62")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="083f0833-0897-4d9e-8ad5-aa263d12a44d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="df0a273b-b25a-45d9-9d7f-df2036661053")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="7e06c1f8-1d05-43d4-9d91-d5fb1cb4c835")>]

In [141]:
company_names=[]
for i in companies_tag:
    company_names.append(i.text)
company_names

['Bion',
 'Catalyst',
 'Catalyst',
 'Catalyst',
 'Catalyst',
 'Industrial Personnel Network',
 'COUTURE AI PRIVATE LIMITED',
 'Applied Materials',
 'Corestrat Labs Private Limited',
 'Bert Labs',
 'TechKnowledgey Pte Ltd',
 'Target Corporation India Pvt Ltd',
 'Kwalee India Pvt Ltd.',
 'Zycus Infotech Pvt Ltd',
 'BRIDGEi2i Analytics Solutions Private Limited',
 'BRIDGEi2i Analytics Solutions Private Limited',
 'Narayana Health',
 'Mobiotics IT Solution Pvt Ltd',
 'Avery Dennison (India) Pvt. Ltd.',
 'Bion']

In [142]:
##here li is the parent tag and span is the tag containing the data therefore used at end
#Also we can span[1] or span[2] if two span tag present..
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location_tags

[<selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="29e0c4ef-5d60-4518-bdb7-6d4fee775b94")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="90124b87-f58f-4940-9830-d308a1f95132")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="bba0af8d-d2fd-4b79-8590-02a12b870fd4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="7a3ae999-b94e-45dd-a698-2e79483e43a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="6439ea3e-9de1-4e9a-84d4-72d83e524cb9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="d47473f2-6ada-4c56-bb11-7ad8c2fad4eb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="2d0069b1-5123-4cb3-93b2-2850b5899302")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="1c2703fa-9ee9-4b83-97f4-96b346ab4e2a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="7ccdca4d-0eeb-4d50-8730-5f2d9c7501cd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="62e5f35f-f468-4542-8281-6f2bea3b92c3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="50634a56-c53d-49fa-8fce-643bacbfb8b2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="3a7f213a-916b-4803-8ed2-d4009d105eaf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="2127cb45-82c5-4217-8e18-03ae5ee7b9f0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="82cb203f-0c52-456a-a69f-ba041037f7f9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="48252a7d-2a9b-44a7-9701-952ed3afd01d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="acd2d500-ece0-4cd8-99d8-508cb948c260")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="181df847-8592-4d8d-9160-a1c5bf7e1ff4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="34326d42-2bba-46f9-9c4d-76949fedcfae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="47a3109c-e9f6-480c-aaa7-7a8823e93938")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b5b9149c36d2971ac0afd853c1a0ddaa", element="5a724a48-25ae-4a79-9d16-6cfa2478ff92")>]

In [143]:
location_list=[]
for i in location_tags:
    location_list.append(i.text)
location_list

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru(HSR Layout)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [144]:
#job description
urls=[]
for j in driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"):
                                           urls.append(j.get_attribute("href"))
urls

['https://www.naukri.com/job-listings-data-scientist-bion-bangalore-bengaluru-2-to-7-years-040320903130?src=jobsearchDesk&sid=16216708832694902&xp=1&px=1',
 'https://www.naukri.com/job-listings-data-scientist-catalyst-bangalore-bengaluru-2-to-7-years-281119905509?src=jobsearchDesk&sid=16216708832694902&xp=2&px=1',
 'https://www.naukri.com/job-listings-data-scientist-python-sql-catalyst-bangalore-bengaluru-2-to-7-years-030918900823?src=jobsearchDesk&sid=16216708832694902&xp=3&px=1',
 'https://www.naukri.com/job-listings-data-scientist-machine-learning-catalyst-bangalore-bengaluru-2-to-7-years-290720902628?src=jobsearchDesk&sid=16216708832694902&xp=4&px=1',
 'https://www.naukri.com/job-listings-data-scientist-python-r-catalyst-bangalore-bengaluru-2-to-6-years-240320902966?src=jobsearchDesk&sid=16216708832694902&xp=5&px=1',
 'https://www.naukri.com/job-listings-data-scientist-bangalore-only-iitand-iim-industrial-personnel-network-bangalore-bengaluru-1-to-6-years-040521001668?src=jobsearchDesk&sid=16216708832694902&xp=6&px=1',
 'https://www.naukri.com/job-listings-data-scientist-couture-ai-private-limited-bangalore-bengaluru-2-to-5-years-130521003858?src=jobsearchDesk&sid=16216708832694902&xp=7&px=1',
 'https://www.naukri.com/job-listings-data-scientist-applied-materials-india-private-limited-bangalore-bengaluru-2-to-4-years-070521901521?src=jobsearchDesk&sid=16216708832694902&xp=8&px=1',
 'https://www.naukri.com/job-listings-data-scientist-corestrat-labs-private-limited-bangalore-bengaluru-2-to-7-years-080521001751?src=jobsearchDesk&sid=16216708832694902&xp=9&px=1',
 'https://www.naukri.com/job-listings-data-scientist-optimus-rl-dl-bert-labs-bangalore-bengaluru-2-to-5-years-120521501073?src=jobsearchDesk&sid=16216708832694902&xp=10&px=1',
 'https://www.naukri.com/job-listings-data-scientist-techknowledgey-pte-ltd-bangalore-bengaluru-0-to-2-years-070521003138?src=jobsearchDesk&sid=16216708832694902&xp=11&px=1',
 'https://www.naukri.com/job-listings-data-scientist-target-corporation-india-pvt-ltd-bangalore-bengaluru-1-to-6-years-100521500309?src=jobsearchDesk&sid=16216708832694902&xp=12&px=1',
 'https://www.naukri.com/job-listings-data-scientist-kwalee-india-pvt-ltd-bangalore-bengaluru-2-to-7-years-171120001467?src=jobsearchDesk&sid=16216708832694902&xp=13&px=1',
 'https://www.naukri.com/job-listings-data-scientist-zycus-infotech-pvt-ltd-bangalore-bengaluru-1-to-6-years-050521901759?src=jobsearchDesk&sid=16216708832694902&xp=14&px=1',
 'https://www.naukri.com/job-listings-data-scientist-bridgei2i-analytics-solutions-private-limited-bangalore-bengaluru-2-to-6-years-110521003546?src=jobsearchDesk&sid=16216708832694902&xp=15&px=1',
 'https://www.naukri.com/job-listings-data-scientist-bridgei2i-analytics-solutions-private-limited-bangalore-bengaluru-2-to-6-years-110521003545?src=jobsearchDesk&sid=16216708832694902&xp=16&px=1',
 'https://www.naukri.com/job-listings-data-scientist-narayana-hrudayalaya-ltd-bangalore-bengaluru-1-to-4-years-290421001155?src=jobsearchDesk&sid=16216708832694902&xp=17&px=1',
 'https://www.naukri.com/job-listings-data-scientist-mobiotics-it-solution-pvt-ltd-bangalore-bengaluru-2-to-5-years-011120000228?src=jobsearchDesk&sid=16216708832694902&xp=18&px=1',
 'https://www.naukri.com/job-listings-data-scientist-avery-dennison-india-pvt-ltd-bangalore-bengaluru-2-to-4-years-070521500049?src=jobsearchDesk&sid=16216708832694902&xp=19&px=1',
 'https://www.naukri.com/job-listings-lead-data-scientist-bion-bangalore-bengaluru-2-to-7-years-040320901798?src=jobsearchDesk&sid=16216708832694902&xp=20&px=1']

In [145]:
description=[]
for i in urls:
    driver.get(i)
    for j in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
        description.append(j.text)
description

["Responsibilities\n\nCollaborate with product and business teams to understand all aspects of the problem\n\nDefine the right target metrics that best represent the end-user value\n\nApply knowledge of ML, statistics, and advanced mathematics to conceptualize, experiment and design an intelligent system\n\nWork with engineers to build the system end-to-end including Big Data pipelines and ensure the serving system is scalable and highly performant.\n\nQualifications\n\nA Bachelor's degree or a higher degree in Computer Science, Statistics, Mathematics or a related field.\n\nStrong problem-solving and programming skills with a deep understanding of data structures and algorithms.\n\nSolid understanding of mathematical underpinnings behind Machine Learning algorithms and proficiency in probability, statistics, linear algebra, calculus, and optimization.\n\nMust have 2+ years of experience in ML with a proven record of successful ML projects with strong individual contribution\n\nExperience with NLP, Distributed Systems, large scale computing, Big Data technologies like Hadoop and Spark are plus.",
 "Responsibilities\n\nCollaborate with product and business teams to understand all aspects of the problem\n\nDefine the right target metrics that best represent the end-user value\n\nApply knowledge of ML, statistics, and advanced mathematics to conceptualize, experiment and design an intelligent system\n\nWork with engineers to build the system end-to-end including Big Data pipelines and ensure the serving system is scalable and highly performant.\nRequired Candidate profile\nQualifications\n\nA Bachelor's degree or a higher degree in Computer Science, Statistics, Mathematics or a related field.\n\nStrong problem-solving and programming skills with a deep understanding of data structures and algorithms.\n\nSolid understanding of mathematical underpinnings behind Machine Learning algorithms and proficiency in probability, statistics, linear algebra, calculus, and optimization.\n\nMust have 2+ years of experience in ML with a proven record of successful ML projects with strong individual contribution\n\nExperience with NLP, Distributed Systems, large scale computing, Big Data technologies like Hadoop and Spark are plus.",
 "Roles and responsibilities \nJob description\n\nSkill: SQL, Python, Business Analysis, Data Science;\n\nExp: 2-7 years;\n\nJob Description Ensuring quality in crowd sourcing model is the biggest challenge to solve for. Being the first data scientist of the company, you shall be responsible for building robust algorithms ensure quality, from scratch.Responsibilities- Develop models to derive maximum quality from crowd sourced data\n\nDerive insights and identify opportunities through the use of algorithmic, statistical, mining & visualisation techniques- Work closely with engineering to implement aforementioned models\nRequired Candidate profile\nRequirements\n\nBachelors or above in Mathematics, Statistics, CS or related fields.\n\nMin. 2 years experience with mathematical modelling, statistical analysis, machine learning, NLP- Must have implemented machine learning based solution which is being used in production\n\nProgramming proficiency, preferably with Python, R, SQL, Java and equivalents- Experience of working with relational and non-relational databasesWe're a fast growing startup, looking for talented and ambitious individuals who want to join us on this journey and build awesome things which can change the way work gets done. You shall get,- Complete Ownership, Flexible timings\n\nWe deal with millions of data points every day and we can assure you that you will have no dearth of data to work with in this job- Pay as per industry standards. Lucrative stock options.\n\nAn awesome office to work in and awesome people to work with- Weekend beer! Munchies on the house )",
 'Roles and Responsibilities\n- Implement data-driven solutions based on advanced ML and optimization algorithms to address business problems\n\n- Research, experiment, and innovate MLstatistical approaches in various application areas of interest and contribute to IP\n\n- Partner with engineering teams to build scalable, efficient, automated ML-based pipelines (trainingevaluationmonitoring)\n\n- Deploy, maintain, and debug MLdecision models in a production environment\n\n- Analyze and assess data to ensure high data quality and correctness of downstream processes\n\n- Communicate results to stakeholders and present datainsights to participate in and drive decision making',
 "What You'll Do :\n\n- Leverage data to perform intensive analysis across all areas of our business to catalyze product development\n\n- Design experiments and interpret the results to draw detailed and actionable conclusions\n\n- Generate and execute on ideas for exploratory analysis to shape future projects and provide recommendations for actions\n\n- Perform time-series analyses, hypothesis testing, and causal analyses to statistically assess relative impact and extract trends\n\n- Create models to enhance understanding of user behavior and predict future performance of cohorts\n\n- Create dashboards and reports to regularly communicate results and monitor key metrics\n\n- Present findings to senior management to guide business decisions\n\n- Collaborate with cross-functional teams across disciplines such as product, engineering, operations, and marketing\n\nRequired Candidate profile\nWhat You'll Need :\n\n- 3-5 years of experience in a quantitative analysis role\n\n- BE/BS/MS in Physics, Economics, Applied Math, Statistics, Engineering, Computer Science, or other quantitative field (advanced degrees are a plus)\n\n- Comfortable writing code and contributing to a code base in Python or R\n\n- Proficient in writing and understanding complex SQL; experience working with large data sets\n\n- Advanced knowledge of experimentation and statistical methods\n\n- Ability to deliver on tight timelines and move quickly while maintaining attention to detail\n\n- Collaborate closely with cross-functional teams to execute on decisions\n\n- Self-driven and proactive with the ability to work in a self-guided manner\n\n- Excellent communication and organization skills",
 'The candidate should have relevant experience in Python, R, Machine Learning, NLP, Deep Learning, CNN, KNN, Neural Network etc of 1 to 7 yrs for various role. Btech candidates 2012-2018 batch can apply for this position (Only IIT / IIM Candidates)',
 'Couture AI Pvt Ltd, Bengaluru, India\ninfo@couture.ai | www.couture.ai\nJob Description: Data Scientist Openings at Couture AI\nCouture AI Platform provides Pluggable Building Blocks to entire\nAI stack, which are used to build and productionize varied\nAbout Company enterprise ML and deep learning usecases. It has enabled some\nof largest global organizations implement specific vertical\ntargeted products build on top of its proprietary AI platform.\nNature of Business Artificial Intelligence Platform\nCompany Website www.couture.ai\nJob Designation Data Scientist / Associate Data Scientist\nJob Location Bengaluru\nBasic Qualifications:\n• Bachelors in Computer Science/Mathematics + Research\n(Machine Learning, Deep Learning, Statistics, Data Mining,\nGame Theory or core mathematical areas) from Tier-1 institutes\n(IITs, IISc, BITS, IIITs and global ranked Univs) with good\nacademic credentials (CGPA).\nExperience:\n• Building large scale AI models and/or systems.\n• Expertise with Data, Machine Learning and Deep learning\n(CNN, RNN, LSTM, RBM, Seq-to-Seq Autoencoders Decoders,\netc.).\n• Strong data structures and algorithms capabilities.\nJob Description &\nSkills Required\nLooking for data science researchers.\n• Strong working knowledge of deep learning, machine\nlearning, and statistics.\n- Domain understanding of Personalization, Search and\nVisual.\n• Strong math skills with statistical modeling and machine\nlearning.\n• Experience in using Python, statistical/machine learning libs.\n• Hands-on experience building models with deep learning\nframeworks (TensorFlow & TF tooling: TFX, TF Serving, Tensor\nBoard, etc.).\n• Ability to think creatively and solve problems.\n\n\n\n\nCouture AI Pvt Ltd, Bengaluru, India\ninfo@couture.ai | www.couture.ai\nPreferred:\n• Publications in highly accredited journals (If available, please\nshare links to your published work.).\n• Or, history of scaling ML/Deep learning algorithms at\nmassively large scale.',
 "Roles and Responsibilities\nWe are looking for data scientists to support market trading and risk management analytics solutions. We are about getting it done and owning what you do. We treat our people equally, fairly and give them the freedom and autonomy to create something awesome. We make mistakes, we learn from them and we back everything up with data and logic. We are on the hunt for exceptional talent who are intellectually curious, analytical, impact-driven, persistent, and not shy about sharing their opinions and recommendations.\n\nWHAT YOU'LL BE DOING\nDesign predictive customer models that enable the business to drive algorithmic approach to trade in securities, pricing, and risk management\nDeliver real impact to the product through rigorous data-driven solutions\nResearch and build scalable models with or without machine learning\nCollaborate to enhance data infrastructure and build a seamless research platform\nUse descriptive statistics and advanced analytics to enable understanding of behaviors and patterns within data.\nTransforms formulated problems into implementation plans for experiments\n\nDesired Candidate Profile\nBachelors/MS in Statistics, Economics or Computer Science\n3+ years of experience in data sciences, research, or business roles\nHigh proficiency with SQL, experience with R, SAS, or Python highly preferred\nDeep understanding of fundamentals of probability and statistics\nExperience with different techniques including clustering, ML algorithms, decision tree, random forest, and experimental design applied to real-world problems.\nPreferred - Numpy, Pandas, GCP\n\nPerks and Benefits\nWork in an open and inclusive culture, with integrated flex working, Competitive benefits\nExcellent workplace benefits\nCore Benefits: Health, Pension, Flexible working\nLearning: Training reimbursement, conference and training sponsorship\nTime Off: Generous vacation and unlimited sick days, competitive paid caregiver leaves",
 'Architect, design, own, and execute the development strategy for Optimus, Bert proprietary distributed AI platform.\nSetup scalable pipelines and processes for data pre-processing/cleaning, feature extraction, dimensionality reduction, model building, and serving.\nUtilize existing and newer algorithms to build the prediction and optimization models from the time series data.\nCollaborate with physics-based modeling team members to pre-train the models before field deployment.\nCollaborate with front-end developers to integrate analytics.\nEntrepreneurial Leadership role, wherein you Innovate every day and do things beyond your current capabilities.\nRequirements:\nExperience: BTech/MTech/MS/PhD in CS/ECE/Statistics or other relevant field from reputed Institutes. 2 to 8 years of Industrial experience.\nExperience in statistical time-series analytics and forecasting: quartiles,\nETS forecast, Holt-Winters, autoregressive techniques ARIMA/SARIMA, GARCH, hybrid GARCH-LSTM.\nApplications to sales/demand forecasting in retail, analytics for industrial IoT time-series data is preferred.\nExperience in RNN/LSTM, Gradient Boosted Machines, SVM, Ensemble techniques.\nExperience in NoSQL DBs, Hadoop, analytics tools: Power BI, Tableau, etc., and data pipelines for ML: Apache Spark Streaming, Storm, Flink, etc., is preferred.',
 "WHAT WE NEED\nPh.D. or Masters or Bachelor's in computer science, Electrical / Computer Engineering\nOperations Research, Industrial Engineering or Mathematics / Statistics\n3- 5 years of relevant working experience\nProficient in RDBMS such as PostgresQL or MySQL.\nExpertise in Python along with expertise in (either one or both) Tensorflow/Pytorch.\nPractical experience in creating large scale recommender systems would be a huge plus (but is not a mandatory requirement)\nExperience in training Transformers from scratch would be a huge plus (but is not mandatory requirement).\nPrior experience of working with Variational Autoencoders would be a huge plus (but is not a mandatory requirement)\nDeep understanding of statistical and predictive modelling concepts\nStrong understanding of the practical applications of machine-learning approaches around supervised and unsupervised learning tasks.\nExperience in building ML models at scale, using real-time big data pipelines on platforms such as Spark/MapReduce.\nFamiliar with noSQL, postGIS, stream processing and distributed computing platforms\nWorking knowledge of Big Data technologies such as Hadoop, MPP Databases, or stream processing techniques.\nExperience working independently and, in a team,\nSelf-motivated, independent learner, and willing to share knowledge with team members\nDetail-oriented and efficient time manager in a dynamic and fast-paced working environment",
 'Core responsibilities are described within this job description. Job duties may change at any time due to business needs.\nQualifications:\nBachelors/Masters equivalent in any Quantitative disciplines (Science, Technology, Engineering, Mathematics)\n1+ years of relevant experience\nStrong analytical thinking skills. Ability to creatively solve business problems, innovating new approaches where required.\nWorking knowledge in Python/R, SQL, Hadoop/Hive. Additional knowledge of Spark, Scala, Java desired but not mandatory\nUnderstanding of foundational mathematics and statistical concepts\nConceptual understanding of analytical techniques like Linear Regression, Logistic Regression, Time-series models, Classification Techniques, etc\nDomain knowledge of Supply chain preferred\nStrong written and verbal communication skills to explain complex analytical methodologies to clients regardless of the client s technical expertise\nStrong team player with ability to collaborate effectively across geographies/ time zones',
 'Kwalee is one of the world\'s leading multiplatform game publishers, with well over 600 million downloads worldwide for mobile hits such as Draw It, Teacher Simulator, Lets Be Cops 3D and Makeover Studio 3D. Alongside this, we also have a growing PC and console team of incredible pedigree that is on the hunt for great new titles to join TENS! and Eternal Hope.\n\nWith a team of talented people collaborating daily between our studios in Leamington Spa, Bangalore and Beijing, or on a remote basis from Turkey, Brazil, the Philippines and many more, we have a truly global team making games for a global audience. And its paying off: Kwalee games have been downloaded in every country on earth! If you think you\'re a good fit for one of our remote vacancies, we want to hear from you wherever you are based.\n\nFounded in 2011 by David Darling CBE, a key architect of the UK games industry who previously co-founded and led Codemasters for many years, our team also includes legends such as Andrew Graham (creator of Micro Machines series) and Jason Falcus (programmer of classics including NBA Jam) alongside a growing and diverse team of global gaming experts. Everyone contributes creatively to Kwalees success, with all employees eligible to pitch their own game ideas on Creative Wednesdays, and were proud to have built our success on this inclusive principle. Could your idea be the next global hit?\n\nAs a Data Scientist you will help utilise masses of data generated by Kwalee players all over the world to solve complex problems using cutting edge techniques.\n\nYou\'ll be part of a team that will be based in the new office that we\'re going to open in Bangalore.\nWhat you tell your friends you do\n"My models optimise the performance of Kwalee games and advertising every day!”\n\nWhat you will really be doing\nBuild data solutions to solve business problems\nUse statistical testing and predictive modelling to recommend and implement changes to marketing strategy along with in game features and design\nLeverage the huge amount of data generated by our players and advertising campaigns everyday to build models and iterate existing services to improve and automate decision making across the company\nWork with the marketing, publishing and development teams to understand the problems they are facing and how to solve them\n\nHow you will be doing this\nYou’ll be part of an agile, multidisciplinary and creative team and work closely with them to ensure the best results.\nYou\'ll think creatively and be motivated by challenges and constantly striving for the best.\nYou’ll work with cutting edge technology, if you need software or hardware to get the job done efficiently, you can get it. We even have a robot!\n\nTeam\nOur talented team is our signature. We have a highly creative atmosphere with more than 150 staff where you’ll have the opportunity to contribute daily to important decisions. You’ll work within an extremely experienced, passionate and diverse team, including David Darling and the creator of the Micro Machines video games.\n\nSkills and requirements\nA degree in a numerically focussed degree discipline such as, Maths, Physics, Economics, Chemistry, Engineering, Biological Sciences\n2+Years experience using Python for data analysis and visualisation and using libraries such as Tensorflow, Keras and Scikit-Learn\nA proven track record of solving problems with data\nKnowledge of NoSQL or SQL databases like Couchbase, Elasticsearch and PostgreSQL\nAn avid interest in the development, marketing and monetisation of mobile games\n\nDesirable\nExperience with AWS - Redshift, EC2, Lambda\nExperience managing data projects from prototype to production tools\n\nWe offer\nWe want everyone involved in our games to share our success, that’s why we have a generous team profit sharing scheme from day 1 of employment\nIn addition to a competitive salary we also offer private medical cover and life assurance\nCreative Wednesdays! (Design and make your own games every Wednesday)\n20 days of paid holidays plus bank holidays\nGreat work-life balance with flexible working hours\nQuarterly team building days - work hard, play hard!\nMonthly employee awards\nFree snacks, fruit and drinks\nOur philosophy\nWe firmly believe in creativity and innovation and that a fundamental requirement for a successful and happy company is having the right mix of individuals. With the right people in the right environment anything and everything is possible',

In [146]:
jobs=pd.DataFrame()
jobs["title"]=job_titles[:10]
jobs["company"]=company_names[:10]
jobs["location"]=location_list[:10]
jobs["job_description"]=description[:10]

In [147]:
jobs

,title,company,location,job_description
0,Data Scientist,Bion,Bangalore/Bengaluru,Responsibilities\n\nCollaborate with product a...
1,Data Scientist,Catalyst,Bangalore/Bengaluru,Responsibilities\n\nCollaborate with product a...
2,Data Scientist - Python/ SQL,Catalyst,Bangalore/Bengaluru,Roles and responsibilities \nJob description\n...
3,Data Scientist - Machine Learning,Catalyst,Bangalore/Bengaluru,Roles and Responsibilities\n- Implement data-d...
4,Data Scientist - Python/r,Catalyst,Bangalore/Bengaluru,What You'll Do :\n\n- Leverage data to perform...
5,Data scientist - Bangalore - only IITand IIM,Industrial Personnel Network,Bangalore/Bengaluru,The candidate should have relevant experience ...
6,Data Scientist,COUTURE AI PRIVATE LIMITED,Bangalore/Bengaluru,"Couture AI Pvt Ltd, Bengaluru, India\ninfo@cou..."
7,Data Scientist,Applied Materials,Bangalore/Bengaluru,Roles and Responsibilities\nWe are looking for...
8,Data Scientist,Corestrat Labs Private Limited,Bangalore/Bengaluru,"Architect, design, own, and execute the develo..."
9,Data Scientist - Optimus ( RL/ DL),Bert Labs,Bangalore/Bengaluru,WHAT WE NEED\nPh.D. or Masters or Bachelor's i...

In [148]:
#Q3: In this question you have to scrape data using the filters available on the webpage as shown below:

In [236]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.naukri.com/"
driver.get(url)

In [237]:
#finding element for job search bar
search_job=driver.find_element_by_id("qsb-keyword-sugg")

In [238]:
# writing on search bar
search_job.send_keys("Data Scientist")

In [239]:
#do click using xpath function
search_btn=driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [153]:
#Now we will see in the window opened by webdriver whether the webpage has opened or not.Lets check it.
#Now first craete 4 empty list.In this list we will store data which will be scrapped.
#We have craeted 4 empty lists for 4 features which we have to extract
#job title ,company names ,locations_list,job_description

In [242]:

filter_btn_loc1=driver.find_element_by_xpath("//a[@class='blue-text filter-more-link']/span")
filter_btn_loc1.click()

In [ ]:
filter_btn_loc=driver.find_element_by_xpath("//div[@class='mt-8 chckBoxCont']/label/i")
filter_btn_loc.click()

In [262]:
filter_btn_close=driver.find_element_by_xpath("//i[@class='naukicon naukicon-cross icon-24']")
filter_btn_close.click()
#<i class="naukicon naukicon-cross icon-24"></i>

In [265]:
title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title_tags

[<selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="7d38d9a2-b82c-466d-b384-67ce76f32dfc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="d9360ecc-9d09-4618-81c0-d4ad1ab5e92a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="625d5576-d5fc-4e98-8226-8711ddcd679c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="6f32cbb2-2a0a-4747-aa9e-4c8b252a25b0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="ec1d04f5-c21a-41d6-bfcc-44fa82826927")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="06c73d9f-96ab-48ff-930a-dff10775284e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="a9bfbcf0-965f-4f81-b37c-f1c5da4c87fc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="286535ec-52c8-4f23-af50-1c3f79159f20")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="b1ef12e3-e998-4dd5-abb3-1eaf8a4b2c3c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="40eb47d7-f8dc-4f25-a6d9-58ff6f6b514f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="6095419e-0854-46eb-8f24-4b044f1158f8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="126988b5-41ad-42ae-8023-d500eb0cd7f4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1fab816e-ca4d-46ea-af36-63d5a83c0ec3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="fed34782-3b96-4d07-addd-934dab5d6b94")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="c9b22037-fae3-4520-8352-89460daf5ebd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="84be09ff-fd4f-48e7-8e0a-5a566996cb6c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="049cd434-5f9b-474e-9c44-218ef5a91a83")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="c0842428-7acc-4ab8-9d8a-529aeef78662")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="e0efde96-8c74-48e3-93e0-2a5c689c5fbb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="cb5ed62b-aa6d-4229-b393-eb4f803f7a58")>]

In [266]:
#now we will extarct text from web element
job_titles=[]
for i in title_tags:
    job_titles.append(i.text)
job_titles

['Data Scientist / Data Analyst -Business Analyst',
 'Big Data - Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Engineer/Data Scientist/Data Analysis',
 'Data Engineer/Data Scientist/Data Analysis',
 'Specialist I - Data Scientist',
 'Data Scientist',
 'Lead Data Scientist',
 'Data Scientist',
 'SDE Lead Data Scientist-L3',
 'Computational Design Lead Data Scientist-L3',
 'Data Scientist',
 'Hiring For Lead data Scientist For Bangalore location',
 'Principal Data Scientist',
 'we are hiring For the role of data engineer\\data scientist',
 'Hiring For DATA Scientist - ON Contract Basis (3-6 Months)',
 'Senior Data Scientist',
 'Senior Data Scientist',
 'Sr. Data Scientist']

In [267]:
companies_tag=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tag

[<selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="151dd13e-9136-42bb-819a-2cd1483e6d2c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="18ddc5c1-0cbb-416a-933d-04301775c526")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="e868159e-2e89-459c-9f31-1053e9c5a90e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="a610a089-8ec8-43fa-b61d-dac7e2369173")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="776d46d6-6187-42fc-8e37-15c6c2b4b09d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="37e94736-6311-4efd-9019-4046073799fb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="485be7d7-04a2-43b1-97fc-39db01a1aa08")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="365e795f-d309-4a1b-bf51-c738a96d7a9c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="347c1716-47d7-48d5-b793-b83689ac248c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="a465a8dc-770f-4e03-83d7-cfac30410fd7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="3971fb2e-1234-4a3d-b7b8-bc10e1d40698")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="fcc3e8b2-0445-4860-a390-eb074a81e2ad")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="b4f0fedc-c484-41bc-bcb0-8be5c1187cfc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="23b6e143-bb62-4dab-a6f3-e7f040575421")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1569c0f7-62dd-4776-b274-a13995cb8bae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1f5d91b8-8896-41c4-92c8-8fae08a19fa3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1b030b82-66e4-43ca-86e2-f9e1f0a85dd0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="583f7afd-b0df-4435-a230-a2bf884d833e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="615a090e-785c-4d16-85fd-983ed41120a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="ce1d739c-bf20-4d42-95bc-9b2e84450092")>]

In [268]:
company_names=[]
for i in companies_tag:
    company_names.append(i.text)
company_names

['Inflexion Analytix Private Limited',
 'Xoriant Solutions Pvt Ltd',
 'TechKnowledgey Pte Ltd',
 'Wipro Limited',
 'NIFTEL COMMUNICATIONS PRIVATE LIMITED',
 'NIFTEL COMMUNICATIONS PRIVATE LIMITED',
 'Philips India Limited',
 'IBM India Pvt. Limited',
 'Intel Technology India Pvt Ltd',
 'Oracle India Pvt. Ltd.',
 'Huawei Technologies India Pvt Ltd',
 'Huawei Technologies India Pvt Ltd',
 'Applied Materials',
 'Societe Generale',
 'NetApp',
 'COLLABERA',
 'GlobalEdx Learning and Technology Solution Pvt Ltd',
 'GO-JEK India',
 'nanobi data and analytics private limited',
 'VALIANCE ANALYTICS PRIVATE LIMITED']

In [269]:
##here li is the parent tag and span is the tag containing the data therefore used at end
#Also we can span[1] or span[2] if two span tag present..
location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
location_tags

[<selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="7d81bc02-1ba1-4c79-a5c5-5c47cc720b18")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="0fcf3d3a-ab5a-4c3e-a64e-68b9e3a0d7f3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="2c824ac7-3801-4884-aafd-aad6d831d809")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="f60af585-8e98-4c35-b340-f9fab4e6db21")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="142cbdab-3d0e-4de7-96eb-d677895c5595")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1540dddc-e1e5-479c-9ec8-230b2740e706")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="0523409e-9a84-4fef-9da5-ff81df8c2c7b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="8232e571-307a-4d14-aa1a-4a52efc944b6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="2545ffee-b9a2-4495-b345-a3116c4a0b16")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="896c4edd-0400-4432-9055-9ac63a489222")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="ecfeb580-dd46-47a7-ae05-2ec3fb9a57cf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="4b77b027-adcd-4553-86d5-5863a3704f02")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="f872fdb4-84d4-48e7-ac5c-cc3f8008fc36")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="b92708cb-3a87-41b5-ba0e-72cc60f1d7d2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="e82c459d-4dcb-4aa9-a7e1-fed8c6c22b0b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="46c63577-2cb5-4d51-85a6-4e390e96204a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="b29adf29-02c5-4795-8c48-b23ea4e16b98")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="cd1a5adb-c406-4bd0-b944-fffa63a33d3f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="c31707b9-528d-430b-963b-a796afe299cb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="3b50bb52-de29-409e-b20c-1ca0bf4b8ce0")>]

In [270]:
location_list=[]
for i in location_tags:
    location_list.append(i.text)
location_list

['Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Kochi/Cochin, Indore, Hyderabad/Secunderabad, Pune, Ahmedabad, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Kolkata, Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru',
 'Noida, Chandigarh, Indore, Gurgaon/Gurugram, Ahmedabad, Jaipur, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Noida, Chandigarh, Indore, Gurgaon/Gurugram, Ahmedabad, Jaipur, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Delhi / NCR']

In [271]:
##here li is the parent tag and span is the tag containing the data therefore used at end
experience_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']//span")
experience_tags

[<selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="f4a67bcb-062b-46a2-b77c-f8299d00f37e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="63ad9b4a-efcc-4579-875e-4c68d14e6de7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="c464538e-4986-4558-abaa-370df09f129d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1dfabb24-b703-4aa2-bbe2-ff7d9526ccaa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="8c6b0129-b155-41dc-a59f-be2ed6d077cb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="170a665c-ba6d-428f-a53d-f43ea59e074b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="08aa1100-aefd-4f6f-9d27-44a2741cec77")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="ca9f1cd2-4177-4923-9c78-19d59189081b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="0f473078-d83d-4068-a133-731c7b664aa8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="557d4aa4-f942-43d4-9197-2d6c021c8f8b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="41517005-34d4-4be1-8ef6-1b6390f806b7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="04f4cfa0-9e71-43bd-8e52-739b1de30677")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="2e6ad244-a64b-4c2e-ad0b-16db936616ef")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="703324b1-34a7-4b85-84b3-1d8a75499b7e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="2d87ccda-0840-45b8-9480-2864a8f1540b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="1428cbfd-864c-4132-9283-052e769f27b4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="ad5491a7-f7c4-4e13-821a-3862dfd0b58f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="cb356505-d320-4a92-8b75-027fd341719a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="c4262a54-aaa8-456b-9bbd-9ae357c5bb8d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="576d555389d1e168e40d87c31b35a740", element="f57426cc-7a21-4728-9d15-c5c5e55500de")>]

In [272]:
experience_list=[]
for i in experience_tags:
    experience_list.append(i.text)
experience_list

['0-3 Yrs',
 '1-3 Yrs',
 '0-2 Yrs',
 '4-9 Yrs',
 '3-8 Yrs',
 '3-8 Yrs',
 '4-7 Yrs',
 '6-8 Yrs',
 '6-10 Yrs',
 '6-10 Yrs',
 '5-8 Yrs',
 '5-8 Yrs',
 '2-4 Yrs',
 '5-9 Yrs',
 '10-15 Yrs',
 '5-8 Yrs',
 '3-8 Yrs',
 '4-11 Yrs',
 '7-9 Yrs',
 '6-8 Yrs']

In [276]:
jobs=pd.DataFrame()
jobs["title"]=job_titles[:10]
jobs["company"]=company_names[:10]
jobs["experience_required"]=experience_list[:10]
jobs["location"]=location_list[:10]

In [277]:
jobs

,title,company,experience_required,location
0,Data Scientist / Data Analyst -Business Analyst,Inflexion Analytix Private Limited,0-3 Yrs,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/..."
1,Big Data - Data Scientist,Xoriant Solutions Pvt Ltd,1-3 Yrs,"Kochi/Cochin, Indore, Hyderabad/Secunderabad, ..."
2,Data Scientist,TechKnowledgey Pte Ltd,0-2 Yrs,Bangalore/Bengaluru
3,Data Scientist,Wipro Limited,4-9 Yrs,"Kolkata, Hyderabad/Secunderabad, Chennai, Bang..."
4,Data Engineer/Data Scientist/Data Analysis,NIFTEL COMMUNICATIONS PRIVATE LIMITED,3-8 Yrs,"Noida, Chandigarh, Indore, Gurgaon/Gurugram, A..."
5,Data Engineer/Data Scientist/Data Analysis,NIFTEL COMMUNICATIONS PRIVATE LIMITED,3-8 Yrs,"Noida, Chandigarh, Indore, Gurgaon/Gurugram, A..."
6,Specialist I - Data Scientist,Philips India Limited,4-7 Yrs,Bangalore/Bengaluru
7,Data Scientist,IBM India Pvt. Limited,6-8 Yrs,Bangalore/Bengaluru
8,Lead Data Scientist,Intel Technology India Pvt Ltd,6-10 Yrs,Bangalore/Bengaluru
9,Data Scientist,Oracle India Pvt. Ltd.,6-10 Yrs,Bangalore/Bengaluru

In [278]:
#Q4: Write a python program to scrape data for first 10 job results for Data scientist Designation in Noida location. 
#    You have to scrape company_name, No. of days ago when job was posted, Rating of the company.

In [305]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.glassdoor.co.in/index.htm"
driver.get(url)

In [306]:
search_job=driver.find_element_by_id("sc.keyword")

In [307]:
# writing on search bar
search_job.send_keys("Data Scientist")

In [310]:
#finding element for job location bar
search_loc=driver.find_element_by_id("sc.location")
#<input id="sc.location" placeholder="Location" type="text" data-test="search-bar-location-input" aria-label="Search Location" class="css-1etjok6" value="Indore" autocomplete="off">

In [311]:
# writing on search bar
search_loc.send_keys("Noida")

In [312]:
#do click using xpath function
search_btn=driver.find_element_by_xpath("//button[@class='gd-ui-button ml-std col-auto SearchStyles__newSearchButton css-iixdfr']")
search_btn.click()
#<button class="gd-ui-button ml-std col-auto SearchStyles__newSearchButton css-iixdfr" type="submit" data-test="search-bar-submit"><span>Search</span></button>

In [286]:
#Now we will see in the window opened by webdriver whether the webpage has opened or not.Lets check it.
#Now first craete 3 empty list.In this list we will store data which will be scrapped.
#We have craeted 3 empty lists for 3 features which we have to extract
#company names ,no of days ago job posted,rating of company

In [315]:
companies_tag=driver.find_elements_by_xpath("//div[@class='d-flex justify-content-between align-items-start']")
companies_tag

[<selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="199f23a7-d72a-4527-b9a2-04b3c87579fe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="8b9ee630-b244-414e-9a06-d471a79ad503")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="563d7a11-8286-468c-88b0-0e6f9a73c566")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="2f59efe4-3b62-47ff-a170-89d2e3912267")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="ca593ebd-d5d9-44fe-b2bf-dbcba292a05a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="45d0f65e-9e80-4476-a2f9-1a74ca0c1919")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="6b469c88-bf27-43c5-8300-bd688de53e67")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="c58329fb-f50b-4d01-8c33-2b253c712b14")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="f891e585-ac48-4b73-906a-5d844474dfa0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="6d2fa160-4c47-49af-9060-51c0b8db0563")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="c75d2082-791c-4851-856d-1d66a4520caa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="a2353407-183d-4622-904d-fd33ed09c163")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="177a9dbb-e200-4b3a-8ad9-956da9747365")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="56cf2efe-b64e-45e3-a4a7-4797d8fcdd91")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="65ab7861-169d-424f-9b2b-49cbab3610e0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="aa21bf6d-4480-4f17-a178-604a1dd3d5c1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="34ce25ac-f9a1-48fd-a3e6-1b2c919d8113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="7ab65b5a-449f-4952-997f-b44b11713a52")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="4ab5c122-d684-4a9e-9747-c623f28bdda2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="93193355-b452-49c4-a289-6eba2cb28580")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="e5f09685-e2c4-4592-9ab1-598f42630303")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="40004957-97b2-4873-86bb-098feae5ae9c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="a7e9f6f6-fdad-46ca-b571-f33ce3004560")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="5cc03e64-ac6d-41be-aca8-637f9095806c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="d0a73628-4cda-43a4-9b94-21f270e8418d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="e690394a-8b63-4643-9dd6-1604e6d0cee0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="b87003d3-02c6-4515-b3b6-9b68704302d9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="290fab7f-0206-4e7d-9585-e6b51e8139d4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="ff41b566-cf94-4f52-8df2-57e8691a64c9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="4bac59b1-09b5-4eab-8755-91e7b20bd8e6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="b67b4160-2b95-4796-a7d2-bb82ccbc4c76")>]

In [316]:
company_names=[]
for i in companies_tag:
    company_names.append(i.text)
company_names

['UnitedHealth Group',
 'Lantern Digital Services',
 'Ericsson',
 'Boston Consulting Group',
 'Gauge Data Solutions',
 'Biz2Credit Inc',
 'Techlive',
 'Sparkbpl',
 'Priority Vendor',
 'Skyjobs hr services',
 'Mansha Solutions',
 'SearchUrCollege',
 'MasterCard',
 'Webhelp',
 'xtLytics',
 'WishFin',
 'Khan Academy',
 'Fitfyles',
 'Siemens Technology and Services Private Limited',
 'Mahajan Imaging',
 'Team Computers',
 'Ank Aha',
 'Transorg Analytics',
 'Profisor Services',
 'Analytics Vidhya',
 'Saffron Consultancy Services',
 'Sentieo',
 'Nihilent',
 'Innovacer',
 'Futures and Careers',
 'ESRI, Inc.']

In [318]:
days_ago=driver.find_elements_by_xpath("//div[@class='d-flex align-items-end pl-std css-mi55ob']")
days_ago

[<selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="66c6fced-84f5-47ff-b7eb-933bb889d818")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="eb4662f1-115c-497f-b1f6-7f2a4e0de113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="f1ae5b22-889a-498f-822e-33892cd7d1ba")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="c4a60470-f80f-4943-8201-0a44baeca239")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="1d7470ec-d6f3-4a38-a698-1cc734b6658b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="1f3da261-1771-4568-aa82-698af598d7de")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="972e3657-8883-4366-abdd-9953b18c4d4f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="152ce398-1233-41a7-9352-f50a86d3e132")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="40c0717c-76b0-48d3-b84b-65edcef0c341")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="2387e1dd-1370-47db-8434-1f24a4199ac9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="97064ef2-0007-41a8-876c-db0fcfdd812a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="c809845e-d8d4-47d8-88ca-f44272a36ce0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="1ff4a47a-091f-44e5-aa51-533dab1df4bb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="291891fa-d415-42c5-9fe3-8c7c031f881f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="5890e1ef-90f0-485f-ac36-8120507faa74")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="323ae1dd-6e3a-40db-bc56-24cdf37acc60")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="6173d602-9941-47ac-b9a2-f24f08262deb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="92a52304-df44-4cc6-ab92-6beb2d7ede6f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="69852da2-358f-4353-93b6-58e7d2fefe24")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="d5b064cf-4730-469c-bf0c-9096e46f1365")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="5adec3a1-3fae-4737-84ca-481fedc76529")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="31d56a19-4d0a-42f5-87a1-a90bdc91fecf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="53c2c084-5cf9-4584-a328-eb58bf33afb7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="f310091c-ce3a-4657-94a4-42bc6c7e066c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="b7fcbfe0-b45c-40b0-87c1-5f75cdc90276")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="5c9dcb25-5e5b-41ff-9245-776b355177c6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="dd21f854-660e-4ce2-9077-4cbf3cf23db3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="aac9bb11-7e51-407e-b54f-ad556df2bda2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="8a752d48-55ea-4937-94a4-4f2df3e29c75")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="15757698-f59b-4c9b-bc80-c822030d57fb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="b83fb362-0fc4-494d-b2ae-5c5f8a09204d")>]

In [319]:
job_posted_days_ago=[]
for i in days_ago:
    job_posted_days_ago.append(i.text)
job_posted_days_ago

['2d',
 '10d',
 '2d',
 '2d',
 '16d',
 '24d',
 '22d',
 '16d',
 '16d',
 '9d',
 '11d',
 '16d',
 '24d',
 '24h',
 '2d',
 '27d',
 '1d',
 '16d',
 '3d',
 '16d',
 '4d',
 '16d',
 '4d',
 '16d',
 '16d',
 '16d',
 '18d',
 '24d',
 '7d',
 '27d',
 '25d']

In [322]:
rating_list=driver.find_elements_by_xpath("//span[@class='css-19pjha7 e1cjmv6j1']")
rating_list
#<span class="css-19pjha7 e1cjmv6j1">3.6<i class="css-0 e1cjmv6j0"></i></span>

[<selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="a17ce333-b3cf-430b-9807-bb3662b559d8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="b0b334f9-6e86-4de8-b539-187b62f76633")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="a6688f24-f9a3-46fb-9dc7-3c150adb4a8b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="77b53387-595c-4dc4-ac66-e54c463e6afa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="2d562790-9e4f-472d-9dd0-21c0e07fdb83")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="ad2c08b5-ef17-48ea-b175-90e88b60b90e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="a8ef39b2-81d3-4b1b-9ca7-bdd337514a19")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="2132a131-b923-412f-bc9d-152ccf8a825f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="91bdaf2e-d737-4516-b659-850969019e44")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="82875f83-30b2-492f-88f2-2318aa399e85")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="679853b1-531d-44c2-bc12-c9e5f897b3c6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="40096182-f866-4560-bb1f-d8afe7ad53da")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="93fcd3dc-ce1f-45e2-b9f0-6e3111790202")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="e8daec54-9250-498d-8220-b8a3981d0fc1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="2be46e49-4219-47db-9715-6a488e0255fd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="9fca2091-7c19-407d-876b-4653ca855d95")>,
 <selenium.webdriver.remote.webelement.WebElement (session="0f7deb13552336f5c7b39c8a2e1923c8", element="2f16e503-d427-46f6-91d8-34ed58b73a61")>]

In [323]:
rating=[]
for i in rating_list:
    rating.append(i.text)
rating

['3.6',
 '4.1',
 '4.1',
 '3.1',
 '3.8',
 '5.0',
 '3.7',
 '3.8',
 '4.1',
 '4.0',
 '4.1',
 '4.0',
 '2.3',
 '4.5',
 '3.7',
 '3.6',
 '4.1']

In [324]:
jobs=pd.DataFrame()

jobs["company"]=company_names[:10]
jobs["Job_posted_no_of days_ago"]=job_posted_days_ago[:10]
jobs["Rating"]=rating[:10]

In [325]:
jobs

                    company Job_posted_no_of days_ago Rating
0        UnitedHealth Group                        2d    3.6
1  Lantern Digital Services                       10d    4.1
2                  Ericsson                        2d    4.1
3   Boston Consulting Group                        2d    3.1
4      Gauge Data Solutions                       16d    3.8
5            Biz2Credit Inc                       24d    5.0
6                  Techlive                       22d    3.7
7                  Sparkbpl                       16d    3.8
8           Priority Vendor                       16d    4.1
9       Skyjobs hr services                        9d    4.0

In [326]:
#Q5: Write a python program to scrape the salary data for Data Scientist designation in Noida location.
#    You have to scrape Company name, Number of salaries, Average salary, Min salary, Max Salary.

In [327]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.glassdoor.co.in/Salaries/index.htm"
driver.get(url)

In [330]:
search_job=driver.find_element_by_id("KeywordSearch")
#<input name="sc.keyword" id="KeywordSearch" class="keyword" type="text" tabindex="0" value="" placeholder="Job Title or Company" data-auto-complete="true" data-ac-version="New" data-test="search-bar-keyword-input" aria-label="Keyword" autocomplete="off">

In [331]:
search_job.send_keys("Data Scientist")

In [332]:
search_loc=driver.find_element_by_id("LocationSearch")
#<input id="LocationSearch" class="loc" type="text" tabindex="0" value="" data-srch-type="popular" data-test="search-bar-location-input" placeholder="Location" aria-label="Location" autocomplete="off">

In [333]:
# writing on search bar
search_loc.send_keys("Noida")

In [334]:
#do click using xpath function
search_btn=driver.find_element_by_xpath("//button[@class='gd-btn-mkt']")
search_btn.click()
#<button class="gd-btn-mkt" id="HeroSearchButton" type="submit" tabindex="0" data-test="search-bar-submit" aria-label="Search"><span>Search</span></button>

In [337]:
companies_tag=driver.find_elements_by_xpath("//p[@class='m-0 ']")
companies_tag

[<selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d007d25b-1cc3-48d1-9bcb-9f363e4b3a86")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d319d8be-0678-49f5-95dd-60047f22ba6b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="fb6d1003-f36d-4047-ab25-e22003845d41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="8cbe0d7e-0530-432c-ad2b-840f08876d7a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="70b0c5f1-a3f6-4d59-81ec-4da0973edd5d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="79fa8deb-adb4-4d6a-813c-da04000bd047")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="6b63e927-ba19-4b94-97b6-3f571cdc225d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="7a38d415-35f7-4b39-8182-46d3d1802914")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="8a00dbdb-c1ea-4c33-81a9-58353a2c2fbe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="b6d4d352-0594-4911-9408-581b8138a8de")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="89ca91fe-6e49-4299-b2f3-c7a7cab27b95")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="667af22a-4606-4bd2-995d-b3cedec7547a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="4ce8eb11-9f94-477f-a977-927e0b79888d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="5391e3ec-5896-4087-a255-c6e950bf2087")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="7b1556ac-d0f9-47ff-a110-ea0af02ad3cd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="a4437e22-e092-495c-8b21-c36e5d4e2742")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="6b0e62e2-c34a-4626-b286-2d952348a275")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="dd13174e-f0d6-41d8-8fdf-5cbf1e41b85f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d7d31459-2883-4430-8f71-1206fcfaae88")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="c6bed0a6-5de7-4490-9805-d4f46332e6f8")>]

In [338]:
company_names=[]
for i in companies_tag:
    company_names.append(i.text)
company_names

['Tata Consultancy Services',
 'IBM',
 'Accenture',
 'Ericsson-Worldwide',
 'Delhivery',
 'UnitedHealth Group',
 'Valiance Solutions',
 'ZS Associates',
 'EXL Service',
 'Optum Global Solutions',
 'Innovaccer',
 'Cognizant Technology Solutions',
 'Optum',
 'Tech Mahindra',
 'OYO',
 'Nagarro',
 'dunnhumby',
 'Vidooly Media Tech',
 'Algo8.ai',
 'Amazon']

In [340]:
No_of_Sal=driver.find_elements_by_xpath("//p[@class='css-1uyte9r css-1kuy7z7 m-0 ']")
No_of_Sal

[<selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="80e509fe-0851-4447-8db1-271ebe8f0897")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="b2cff85c-30c4-4c99-8d50-a0783940d677")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="f078fae3-3122-4ddf-a99b-61f24f8a2df4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="97210bd9-893c-451f-9e5f-db1d9207feec")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="179b83c1-ba36-4dae-8baf-b18d5f2de478")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="a7cda2d8-6cf5-4919-942b-511533e42863")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="50ff2506-398c-4acf-bf76-f67241513d8c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="758ec03d-ff97-4fde-9672-c5fa255c03b0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="8f09431d-0544-4a5c-8b67-7c2bef361f4e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="032957bf-3c52-409a-a9d6-f26979bff5a9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="88acfac0-b031-45b4-b471-4a334c3498e6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="2380b127-15a8-4c49-9575-c4e92f0ef61d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="3e83c2ef-62cc-41fa-93d6-e6ba44bd8d4c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="5490fd71-b10a-4453-bcba-3172d6c011e9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="7fa0957a-5fab-4990-8535-f4e18d542039")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="f15d5a8e-982a-4c67-8a58-a4342546aec4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="1787b80b-a54e-4a0d-b175-68068262cb40")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="ba98ec68-3729-426c-b41c-91f5fc6bc095")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="6d14e5eb-2f37-4c8d-8302-9806fd8d2228")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="cc33216f-d8bf-496a-8cb4-90644e6e78e8")>]

In [341]:
No_of_Sal_list=[]
for i in No_of_Sal:
    No_of_Sal_list.append(i.text)
No_of_Sal_list

['17 salaries',
 '15 salaries',
 '14 salaries',
 '14 salaries',
 '14 salaries',
 '11 salaries',
 '9 salaries',
 '8 salaries',
 '8 salaries',
 '8 salaries',
 '8 salaries',
 '6 salaries',
 '6 salaries',
 '5 salaries',
 '5 salaries',
 '5 salaries',
 '5 salaries',
 '5 salaries',
 '5 salaries',
 '4 salaries']

In [343]:
Avg_Sal=driver.find_elements_by_xpath("//div[@class='col-2 d-none d-md-flex flex-row justify-content-end']")
Avg_Sal
#<div class="col-2 d-none d-md-flex flex-row justify-content-end"><strong>₹ 6,14,306</strong>/<!-- -->yr</div>

[<selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="9e0aefa3-6274-4339-b572-192a2138d6e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="3220ba32-70c7-4790-84b5-be0a206753b1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="bfb5da2c-8da7-40c0-8a09-2aac8d9ff8d5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="99fc11c0-04cc-4baf-b160-89a4c988ecc8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="ab5b0490-fcb5-4edf-a7b7-ba3a083992a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="03c9a731-ab09-42a7-8155-c4adaaa7e130")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="33bd1039-1f85-45b1-ba04-3e3bc8e9066c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="fd9afeeb-ad7c-45ec-8a1f-25b0871ff327")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d7c65484-bdd3-44ce-9e53-729f84964233")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="ce5e4833-4702-4f3b-92ba-85d72130bbf2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="f34d0c2b-bb5f-4b38-9f70-ae355f098a9f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="4d1b3e90-00af-4c64-85ee-bfa86a74a933")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="814d31fb-ad1c-481b-ba33-51ef34ef6e0d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="646be450-9c4b-4e45-9a2a-5e5d9580153a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="57e03bbf-ff7b-4179-afe9-b0a8870fdad0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="cdacede2-1a7a-4b51-bd8a-4c9a3afd3b22")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="422b2360-0362-49d2-99d3-4053ac693293")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="8a8cb881-ac46-4bf9-8eb9-99a64a6e3a4c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="3e2391cc-b421-4e92-96cd-002eff3c8840")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d986ded9-82d9-49c4-9dc1-d48fe184eb96")>]

In [345]:
Avg_Sal_list=[]
for i in Avg_Sal:
    Avg_Sal_list.append(i.text)
Avg_Sal_list

['₹ 6,14,306\n/yr',
 '₹ 9,00,000\n/yr',
 '₹ 11,46,533\n/yr',
 '₹ 7,38,057\n/yr',
 '₹ 12,39,781\n/yr',
 '₹ 13,36,142\n/yr',
 '₹ 8,15,192\n/yr',
 '₹ 11,35,221\n/yr',
 '₹ 11,44,243\n/yr',
 '₹ 14,13,288\n/yr',
 '₹ 12,07,110\n/yr',
 '₹ 10,07,410\n/yr',
 '₹ 13,18,851\n/yr',
 '₹ 10,52,718\n/yr',
 '₹ 14,13,078\n/yr',
 '₹ 9,61,653\n/yr',
 '₹ 11,00,000\n/yr',
 '₹ 15,887\n/mo',
 '₹ 6,75,000\n/yr',
 '₹ 15,00,000\n/yr']

In [350]:
min_Sal=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__values d-flex justify-content-between ']/span[1]")
min_Sal
#<div class="common__RangeBarStyle__values d-flex justify-content-between "><span class="">₹343K</span><span class="">₹1,250K</span></div>

[<selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="851fa119-86c8-42c0-a696-f13710296079")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="b354b541-f10a-40e6-942b-24bf3c3575fd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="669d18f1-1822-41ed-91a5-26c6253aa30e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="71362444-e1a5-4d01-8809-4e9f00541684")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="ab972435-d587-4943-8ff8-cc2ec79e7543")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="13d79bb7-f8bf-4e00-b9bf-bc7ebcc4a689")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="12775d7b-e7c3-424f-b721-c048ff4d2850")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d8ccd7ec-ad2a-44c2-8655-d8cde37fc543")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="390b21e3-a16a-4178-9a79-a0bf1d30fb7b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="7fbba226-df6e-46f1-9045-6cb83e309ae5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="f3a08246-7418-4d7e-a35b-4ef9b77175de")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="5d774fb5-0b47-4977-ab66-c2f522071e57")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="db8bbdcc-3315-4c3c-a2e5-79c08d7f455d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="1633c68d-9982-4450-80ce-968527b4ba26")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="6b3ac681-6ee9-44db-b062-bcc95a70dc2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="45a59269-afed-407b-9040-2b31de5db527")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="662564e0-8323-4bca-8667-55ba77deb879")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="e7b45b66-de92-4c77-aa1f-4a86762e632e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="38726942-34af-4aec-a10e-ed7f3aae637e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="380a2fc4-88d2-4909-8d19-b680404cbee9")>]

In [351]:
Min_Sal_list=[]
for i in min_Sal:
    Min_Sal_list.append(i.text)
Min_Sal_list

['₹343K',
 '₹586K',
 '₹577K',
 '₹355K',
 '₹450K',
 '₹1,069K',
 '₹502K',
 '₹202K',
 '₹575K',
 '₹1,014K',
 '₹620K',
 '₹792K',
 '₹807K',
 '₹405K',
 '₹971K',
 '₹400K',
 '₹817K',
 '₹12K',
 '₹86K',
 '₹772K']

In [352]:
max_Sal=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__values d-flex justify-content-between ']/span[2]")
max_Sal

[<selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="865b2792-0207-4333-9dcb-46e03dffe626")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="c655d088-5587-4ac0-9c1f-ea18da6beb22")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="cc82eec6-718b-4be6-b0b1-331c6ee3de8e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="6b6fa4b3-601a-40ac-9f62-d16f6ccdfdff")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="a8a6afa0-b651-4062-8b3a-c1648f2d805d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="a5dfe9f7-f880-4c3f-b317-06f05e56c651")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="19fad536-2aa6-44bf-a348-60b8536ec385")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="4cc7a693-41e8-44b5-b450-3ad170d4f532")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="7adafe73-a4bb-4bc5-9d8e-96d301e67e97")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="40483d33-0a81-43ff-bb51-36254e2344f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="41fefe5a-b9aa-41b1-a27c-8da101225711")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="46d84fc2-d94f-470d-bba1-6e146346b12c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="22891591-1139-41ba-b516-38618f949596")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="558e0b9f-c506-4b3d-b222-e31240034a99")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="e7507f7d-6882-4be2-b25f-eb4e31c8ef7b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="d9cd0ec5-cc7d-4f83-97be-9c86a0333f8f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="95168c4d-f9fc-4384-896e-9befe6511b01")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="cde5c3a8-ac02-434b-a3c9-0560b45acdbc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="5a6c6e9b-91dd-4706-a310-4ce7874bb251")>,
 <selenium.webdriver.remote.webelement.WebElement (session="24e8d1043883e9d49fbc689d71c0d2f8", element="ff999d62-1ac2-4ed5-95dc-5ffb8ae50dab")>]

In [353]:
Max_Sal_list=[]
for i in max_Sal:
    Max_Sal_list.append(i.text)
Max_Sal_list

['₹1,250K',
 '₹2,730K',
 '₹2,213K',
 '₹1,613K',
 '₹11,622K',
 '₹1,520K',
 '₹1,465K',
 '₹1,809K',
 '₹1,520K',
 '₹2,149K',
 '₹1,695K',
 '₹1,263K',
 '₹1,986K',
 '₹1,703K',
 '₹1,883K',
 '₹1,124K',
 '₹2,006K',
 '₹63K',
 '₹1,358K',
 '₹2,091K']

In [358]:
jobs=pd.DataFrame()

jobs["Company"]=company_names[:10]
jobs["Number_of_Salary"]=No_of_Sal_list[:10]
jobs["Average_Salary"]=Avg_Sal_list [:10]
jobs["Minimum_Salary"]=Min_Sal_list[:10]
jobs["Maximum_Salary"]=Max_Sal_list [:10]

In [359]:
jobs

,Company,Number_of_Salary,Average_Salary,Minimum_Salary,Maximum_Salary
0,Tata Consultancy Services,17 salaries,"₹ 6,14,306\n/yr",₹343K,"₹1,250K"
1,IBM,15 salaries,"₹ 9,00,000\n/yr",₹586K,"₹2,730K"
2,Accenture,14 salaries,"₹ 11,46,533\n/yr",₹577K,"₹2,213K"
3,Ericsson-Worldwide,14 salaries,"₹ 7,38,057\n/yr",₹355K,"₹1,613K"
4,Delhivery,14 salaries,"₹ 12,39,781\n/yr",₹450K,"₹11,622K"
5,UnitedHealth Group,11 salaries,"₹ 13,36,142\n/yr","₹1,069K","₹1,520K"
6,Valiance Solutions,9 salaries,"₹ 8,15,192\n/yr",₹502K,"₹1,465K"
7,ZS Associates,8 salaries,"₹ 11,35,221\n/yr",₹202K,"₹1,809K"
8,EXL Service,8 salaries,"₹ 11,44,243\n/yr",₹575K,"₹1,520K"
9,Optum Global Solutions,8 salaries,"₹ 14,13,288\n/yr","₹1,014K","₹2,149K"

In [360]:
#Q6 : Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:
#. Brand
#. Product Description
#. Price
#. Discount %

In [365]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.flipkart.com/"
driver.get(url)

In [366]:
user_inp=input("enter the product you want to search :")

enter the product you want to search :sunglasses

In [377]:
#finding element for job search bar
search_bar=driver.find_element_by_class_name("_3704LK")      #locating search bar by id
                                           
search_bar.send_keys(user_inp)

In [378]:
search_button=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")             
search_button.click()

In [383]:
import time
brand_list=[]
product_des_list=[]
price_list=[]
discount_list=[]

In [384]:
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        brand_list.append(j.text)
    for k in driver.find_elements_by_xpath("//a[@class='IRpwTa']"):
        product_des_list.append(k.text)
    for m in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        price_list.append(m.text)
    for n in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']"):
        discount_list.append(n.text)
    driver.find_element_by_xpath("//a[@class='_1LKTO3']").click()
    time.sleep(4)

In [390]:
Product=pd.DataFrame()


Product["Brand"]=brand_list[:100]
Product["Description"]=product_des_list[:100]
Product["Price"]=price_list[:100]
Product["Discount"]=discount_list[:100]

In [391]:
Product

,Brand,Description,Price,Discount
0,Villain,Others Retro Square Sunglasses (Free Size),₹599,20% off
1,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹499,77% off
2,Silver Kartz,UV Protection Oval Sunglasses (56),₹299,75% off
3,NuVew,"UV Protection, Gradient Cat-eye Sunglasses (63)",₹395,74% off
4,elegante,UV Protection Wrap-around Sunglasses (Free Size),₹499,66% off
5,Singco India,UV Protection Round Sunglasses (Free Size),₹205,79% off
6,ROYAL SON,"UV Protection, Gradient Wayfarer Sunglasses (55)",₹217,78% off
7,DEIXELS,UV Protection Wayfarer Sunglasses (Free Size),₹200,59% off
8,ROZZETTA CRAFT,"UV Protection, Gradient Round Sunglasses (Free...",₹449,77% off
9,AISLIN,"UV Protection, Gradient Round, Shield Sunglass...",₹395,77% off
10,PHENOMENAL,"UV Protection, Mirrored Retro Square Sunglasse...",₹399,80% off
11,ROYAL SON,UV Protection Rectangular Sunglasses (58),₹474,68% off
12,hipe,Mirrored Wayfarer Sunglasses (55),₹219,78% off
13,ROYAL SON,UV Protection Wayfarer Sunglasses (55),₹664,66% off
14,ROYAL SON,UV Protection Sports Sunglasses (Free Size),₹265,79% off
15,hipe,"Polarized, UV Protection Aviator Sunglasses (F...",₹319,83% off
16,ROZZETTA CRAFT,Mirrored Aviator Sunglasses (55),₹449,77% off
17,ROYAL SON,UV Protection Retro Square Sunglasses (Free Size),₹379,74% off
18,Flizz,Mirrored Aviator Sunglasses (Free Size),₹399,81% off
19,ROYAL SON,UV Protection Shield Sunglasses (Free Size),₹399,73% off
20,Fastrack,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹759,15% off
21,Fastrack,"UV Protection, Mirrored Clubmaster Sunglasses ...",₹777,22% off
22,PHENOMENAL,UV Protection Round Sunglasses (53),₹319,84% off
23,LIZA ANGEL,"Polarized, UV Protection Aviator Sunglasses (58)",₹259,67% off
24,SRPM,UV Protection Clubmaster Sunglasses (Free Size),₹189,62% off
25,ROYAL SON,"UV Protection, Polarized Wayfarer Sunglasses (56)",₹711,64% off
26,PHENOMENAL,"Mirrored, UV Protection, Gradient Round Sungla...",₹319,84% off
27,Fastrack,"UV Protection, Riding Glasses Wayfarer Sunglas...",₹759,15% off
28,hipe,"UV Protection, Gradient Wayfarer Sunglasses (53)",₹210,85% off
29,NuVew,"UV Protection, Gradient Oval Sunglasses (58)",₹396,74% off
...,...,...,...,...
70,Fastrack,UV Protection Aviator Sunglasses (58),₹759,15% off
71,ROZZETTA CRAFT,Polarized Rectangular Sunglasses (65),₹499,80% off
72,Fastrack,"UV Protection, Mirrored Round Sunglasses (Free...","₹1,123",13% off
73,ROYAL SON,UV Protection Aviator Sunglasses (58),₹699,65% off
74,hipe,"UV Protection, Mirrored Aviator Sunglasses (Fr...",₹219,86% off
75,Fastrack,UV Protection Wayfarer Sunglasses (57),"₹1,115",14% off
76,hipe,"UV Protection, Mirrored Wayfarer Sunglasses (53)",₹199,80% off
77,Fastrack,Polarized Rectangular Sunglasses (65),₹559,30% off
78,GANSTA,Others Retro Square Sunglasses (Free Size),₹199,80% off
79,ROYAL SON,"UV Protection, Gradient Rectangular Sunglasses...",₹699,65% off
80,Villain,UV Protection Oval Sunglasses (56),₹599,20% off
81,ROZZETTA CRAFT,"UV Protection, Gradient Cat-eye Sunglasses (63)",₹499,77% off
82,Silver Kartz,UV Protection Wrap-around Sunglasses (Free Size),₹299,75% off
83,NuVew,UV Protection Round Sunglasses (Free Size),₹395,74% off
84,elegante,"UV Protection, Gradient Wayfarer Sunglasses (55)",₹499,66% off
85,Singco India,UV Protection Wayfarer Sunglasses (Free Size),₹205,79% off
86,ROYAL SON,"UV Protection, Gradient Round Sunglasses (Free...",₹217,78% off
87,DEIXELS,"UV Protection, Gradient Round, Shield Sunglass...",₹200,59% off
88,ROZZETTA CRAFT,"UV Protection, Mirrored Retro Square Sunglasse...",₹449,77% off
89,AISLIN,UV Protection Rectangular Sunglasses (58),₹395,77% off
90,PHENOMENAL,Mirrored Wayfarer Sunglasses (55),₹399,80% off
91,ROYAL SON,Polarized Retro Square Sunglasses (58),₹474,68% off
92,hipe,UV Protection Wayfarer Sunglasses (55),₹219,78% off
93,ROYAL SON,UV Protection Sports Sunglasses (Free Size),₹854,57% off
94,ROYAL SON,"Polarized, UV Protection Aviator Sunglasses (F...",₹265,79% off
95,hipe,Mirrored Aviator Sunglasses (55),₹319,83% off
96,ROZZETTA CRAFT,UV Protection Retro Square Sunglasses (Free Size),₹449,77% off
97,ROYAL SON,UV Protection Shield Sunglasses (Free Size),₹379,74% off
98,Flizz,"Mirrored, UV Protection Wayfarer Sunglasses (F...",₹399,81% off
99,ROYAL SON,"UV Protection, Mirrored Clubmaster Sunglasses ...",₹664,66% off

In [ ]:
#Q7: Scrape 100 reviews data from flipkart.com for iphone11 phone.
#You have to go the link: https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace.

In [392]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace"
driver.get(url)
#https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace.

In [395]:
rating_list=driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
rating_list
#<div class="_3LWZlK _1BLPMq">5<img src="" class="_1wB99o"></div>

[<selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="bbea6064-b3df-4191-b710-04e6e4d60d7a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="cf58b018-44dd-46df-818c-76cb1ec920a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="ea534f41-c903-455c-96a2-8305b74d908c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="69fb0bca-1518-464c-bf3e-d880d23c9918")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="bfa17fcf-2389-4b26-a9c2-6506f74dbf45")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="55ef2304-baa6-4ff7-9ad8-fb12d4d244be")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="26e0d23e-498d-4d3b-a22a-6b992c0d28b8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="1dfec2a1-726c-4c5b-bafe-985e9bb3632d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="8b4cbd70-442f-45e4-8945-8d4b2578aec2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="b938aae9f13d4ea350e36f3034a0edf0", element="d909e4b4-70f9-47a3-aa34-22cadfc65af8")>]

In [399]:
import time
Rating_list=[]
Review_sum=[]
Full_review=[]

In [403]:
for i in range(0,10):
    for j in driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']"):
        Rating_list.append(j.text)
    for k in driver.find_elements_by_xpath("//p[@class='_2-N8zT']"):
        Review_sum.append(k.text)
    for m in driver.find_elements_by_xpath("//div[@class='t-ZTKy']"):
        Full_review.append(m.text)
    driver.find_element_by_xpath("//a[@class='_1LKTO3']").click()
    time.sleep(2)

#<div class="_3LWZlK _1BLPMq">5<img src="" class="_1wB99o"></div>
#<p class="_2-N8zT">Brilliant</p>
#<div class="t-ZTKy"><div><div class="">The Best Phone for the Money<br><br>The iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.<br><br>Compelling ultra-wide camera<br>New Night mode is excellent<br>Long battery life</div><span class="_1H-bmy"><span>READ MORE</span></span></div></div>

#<a class="_1LKTO3" href="/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&amp;lid=LSTMOBFKCTSVZAXUHGREPBFGI&amp;marketplace=FLIPKART&amp;page=2"><span>Next</span></a>
    
#<div class="_3UAT2v _16PBlm"><span class="">All 4572 reviews</span></div>
#all_rev_btn=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
#all_rev_btn.click()

In [406]:
Detail=pd.DataFrame()
Detail["Rating"]=Rating_list[:100]
Detail["Review_Summary"]=Review_sum[:100]
Detail["Review"]=Full_review[:100]

In [407]:
Detail

,Rating,Review_Summary,Review
0,5,Brilliant,The Best Phone for the Money\n\nThe iPhone 11 ...
1,5,Perfect product!,Amazing phone with great cameras and better ba...
2,5,Great product,Amazing Powerful and Durable Gadget.\n\nI’m am...
3,5,Worth every penny,Previously I was using one plus 3t it was a gr...
4,4,Good choice,So far it’s been an AMAZING experience coming ...
5,5,Highly recommended,iphone 11 is a very good phone to buy only if ...
6,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
7,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
8,5,Fabulous!,This is my first iOS phone. I am very happy wi...
9,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
10,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
11,5,Worth every penny,It’s been almost a month since I have been usi...
12,5,Terrific,Really worth of money. i just love it. It is t...
13,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
14,4,Nice product,Awesome Phone. Slightly high price but worth. ...
15,5,Highly recommended,It's my first time to use iOS phone and I am l...
16,5,Wonderful,This is my first ever I phone. Before this I w...
17,5,Classy product,Superb Product !!!\nA big and worthy upgrade f...
18,5,Brilliant,"I have migrated from OP 7pro... and trust me, ..."
19,5,Must buy!,It’s an amazing product from apple and the cam...
20,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
21,5,Worth every penny,It’s been almost a month since I have been usi...
22,5,Terrific,Really worth of money. i just love it. It is t...
23,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
24,4,Nice product,Awesome Phone. Slightly high price but worth. ...
25,5,Highly recommended,It's my first time to use iOS phone and I am l...
26,5,Wonderful,This is my first ever I phone. Before this I w...
27,5,Classy product,Superb Product !!!\nA big and worthy upgrade f...
28,5,Brilliant,"I have migrated from OP 7pro... and trust me, ..."
29,5,Must buy!,It’s an amazing product from apple and the cam...
...,...,...,...
70,5,Perfect product!,Iphone is just awesome.. battery backup is ver...
71,5,Worth every penny,It’s been almost a month since I have been usi...
72,5,Terrific,Really worth of money. i just love it. It is t...
73,5,Simply awesome,"Excellent camera, good performance, no lag. Th..."
74,4,Nice product,Awesome Phone. Slightly high price but worth. ...
75,5,Highly recommended,It's my first time to use iOS phone and I am l...
76,5,Wonderful,This is my first ever I phone. Before this I w...
77,5,Classy product,Superb Product !!!\nA big and worthy upgrade f...
78,5,Brilliant,"I have migrated from OP 7pro... and trust me, ..."
79,5,Must buy!,It’s an amazing product from apple and the cam...
80,5,Brilliant,The Best Phone for the Money\n\nThe iPhone 11 ...
81,5,Perfect product!,Amazing phone with great cameras and better ba...
82,5,Great product,Amazing Powerful and Durable Gadget.\n\nI’m am...
83,5,Worth every penny,Previously I was using one plus 3t it was a gr...
84,4,Good choice,So far it’s been an AMAZING experience coming ...
85,5,Highly recommended,iphone 11 is a very good phone to buy only if ...
86,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
87,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
88,5,Fabulous!,This is my first iOS phone. I am very happy wi...
89,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...
90,5,Brilliant,The Best Phone for the Money\n\nThe iPhone 11 ...
91,5,Perfect product!,Amazing phone with great cameras and better ba...
92,5,Great product,Amazing Powerful and Durable Gadget.\n\nI’m am...
93,5,Worth every penny,Previously I was using one plus 3t it was a gr...
94,4,Good choice,So far it’s been an AMAZING experience coming ...
95,5,Highly recommended,iphone 11 is a very good phone to buy only if ...
96,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
97,5,Perfect product!,Value for money❤️❤️\nIts awesome mobile phone ...
98,5,Fabulous!,This is my first iOS phone. I am very happy wi...
99,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...

In [408]:
#Q8: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field.

In [423]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.flipkart.com/"
driver.get(url)

In [424]:
user_inp=input("enter the product you want to search :")

enter the product you want to search :sneaker

In [425]:
#finding element for job search bar
search_bar=driver.find_element_by_class_name("_3704LK")      #locating search bar by id
                                           
search_bar.send_keys(user_inp)

In [427]:
search_button=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")             
search_button.click()

In [428]:
import time
brand_list=[]
product_des_list=[]
price_list=[]
discount_list=[]

In [440]:
for i in range(0,4):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        brand_list.append(j.text)
    for k in driver.find_elements_by_xpath("//a[@class='IRpwTa']"):
        product_des_list.append(k.text)
    for m in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        price_list.append(m.text)
    for n in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']"):
        discount_list.append(n.text)
    driver.find_element_by_xpath("//a[@class='_1LKTO3']").click()
    time.sleep(2)
    
#<div class="_2WkVRV">DUCATI</div>
#<a class="IRpwTa" title="Sneakers For Men" target="_blank" rel="noopener noreferrer" href="/ducati-sneakers-men/p/itmd9c180ebdb96e?pid=SHOFNHE4ZYYK8MVW&amp;lid=LSTSHOFNHE4ZYYK8MVWXEJRTS&amp;marketplace=FLIPKART&amp;q=sneakers&amp;store=osp%2Fcil%2Fe1f&amp;srno=s_1_1&amp;otracker=search&amp;otracker1=search&amp;fm=SEARCH&amp;iid=en_rMG0w%2Bh3MuryAhJ0liHmjkpfroT4zuxgQXiuryP8l6w6eP7rLZ%2BIGOouqJr7v4ZiPtMDdXx4dJewMcLHsRRydA%3D%3D&amp;ppt=sp&amp;ppn=sp&amp;ssid=x5c4g23txs0000001621701745524&amp;qH=a1743c0d39461290">Sneakers For Men</a>
#<a class="IRpwTa _2-ICcC" title="Rockstyle Trending Multicolor Ultralight canvas Sport/ Training Lace-up Morning / Evening walk Dating Running Shoes For Men | sports shoes for men | Latest Stylish Casual sneakers for men | Lace up lightweight shoes for running, walking, gym, trekking, hiking &amp; party Sneakers For Men" target="_blank" rel="noopener noreferrer" href="/ktiz-rockstyle-trending-multicolor-ultralight-canvas-sport-training-lace-up-morning-evening-walk-dating-running-shoes-men-sports-latest-stylish-casual-sneakers-lace-up-lightweight-running-walking-gym-trekking-hiking-party/p/itm36847ea3fc492?pid=SHOFYPTAVZDHWZU2&amp;lid=LSTSHOFYPTAVZDHWZU2WVIZ5U&amp;marketplace=FLIPKART&amp;q=sneakers&amp;store=osp%2Fcil%2Fe1f&amp;srno=s_2_41&amp;otracker=search&amp;otracker1=search&amp;fm=SEARCH&amp;iid=05e38905-598c-4f4e-a0d9-d894af81705f.SHOFYPTAVZDHWZU2.SEARCH&amp;ppt=sp&amp;ppn=sp&amp;ssid=x5c4g23txs0000001621701745524&amp;qH=a1743c0d39461290">Rockstyle Trending Multicolor Ultralight canvas Sport/ ...</a>

In [443]:
Product=pd.DataFrame()


Product["Brand"]=brand_list[:100]
Product["Description"]=product_des_list[:100]
Product["Price"]=price_list[:100]
Product["Discount"]=discount_list[:100]

In [445]:
Product

,Brand,Description,Price,Discount
0,DUCATI,Classy Sneakers For Men,"₹1,924",47% off
1,DUCATI,Sneakers For Men,"₹1,199",67% off
2,Robbie jones,shoes for boys Sneakers For Men,₹379,62% off
3,Robbie jones,shoes for boys Sneakers For Men,₹474,52% off
4,HOTSTYLE,Sneakers For Men,₹283,43% off
5,Numenzo,Premium quality Sneakers For Men,₹399,60% off
6,ORICUM,1002 Sneakers For Men,₹377,62% off
7,Stefano Rads,Latest Design Sneakers For Men,₹229,67% off
8,Shoes Bank,Rockstyle Trending Multicolor Ultralight canva...,₹349,65% off
9,VIPSJAZZY,Sneakers For Men,₹419,58% off
10,Echor,Sneakers For Men,₹569,43% off
11,BRUTON,Sneakers for man Sneakers For Men,₹499,85% off
12,aadi,White Shoes For Men | Casual White Laceups Sho...,₹298,70% off
13,Kavon,Mens Casual Sneakers Wallking Running Smarts S...,₹370,62% off
14,Birde,M K Footwear 702_Blue Sneakers For Men,₹757,62% off
15,VORII,Sneakers For Men,₹379,62% off
16,"""trend""",Sneakers For Men,₹426,78% off
17,Kraasa,Classy Sneakers For Men,₹416,58% off
18,Echor,Sneakers For Men,₹569,43% off
19,Fzzirok,shoes for boys Sneakers For Men,₹499,50% off
20,SCATCHITE,shoes for boys Sneakers For Men,₹398,60% off
21,World Wear Footwear,Sneakers For Men,₹499,81% off
22,Robbie jones,Premium quality Sneakers For Men,₹428,57% off
23,Fzzirok,1002 Sneakers For Men,₹449,55% off
24,Magnolia,Latest Design Sneakers For Men,₹305,69% off
25,bluemaker,Rockstyle Trending Multicolor Ultralight canva...,₹474,52% off
26,3SIX5,Sneakers For Men,₹214,57% off
27,T-ROCK,Sneakers For Men,₹378,62% off
28,SWIGGY,Sneakers for man Sneakers For Men,₹719,71% off
29,DUCATI,White Shoes For Men | Casual White Laceups Sho...,"₹1,987",44% off
...,...,...,...,...
70,M K FOOTWEAR,Sneakers For Men,₹389,23% off
71,SPARX,Sneakers For Men,₹769,68% off
72,PUMA,Casual Sneakers Shoes For Men Sneakers For Men,"₹1,047",58% off
73,Treadfit,Sneakers For Men,₹419,36% off
74,Jack Diamond,Sneakers Sneakers For Men,₹635,64% off
75,Deals4you,Sneakers For Men,₹359,70% off
76,TR,Combo pack of 2 casual sneaker shoes for men S...,₹599,36% off
77,Jack Diamond,White Sneaker For Men's/Boy's Sneakers For Men,₹631,53% off
78,Imcolus,Combo Pack Of 4 Canvas Sneakers For Men,₹464,50% off
79,BigForest,Sneakers For Men,₹499,47% off
80,DUCATI,Sneakers For Men,"₹1,924",67% off
81,DUCATI,Combo Pack of 4 Casual Shoes Sneakers For Men,"₹1,199",62% off
82,Robbie jones,Latest Stylish Casual sneakers for men | Lace ...,₹379,52% off
83,Robbie jones,Fashionable casual sneakers shoes for men Snea...,₹474,43% off
84,HOTSTYLE,Series 7 Sneakers For Men,₹283,60% off
85,Numenzo,Sneakers Sneakers For Men,₹399,62% off
86,ORICUM,Combo Pack of 4 Latest Collection Stylish Casu...,₹377,67% off
87,Stefano Rads,Casual Sneakers Black Shoes For Men Sneakers F...,₹229,65% off
88,Shoes Bank,Sneakers For Men,₹349,58% off
89,VIPSJAZZY,White Sneakers Sneakers For Men,₹419,43% off
90,Echor,casual for men (blue 06) Sneakers For Men,₹569,85% off
91,BRUTON,ORIFWSH(OR)-1077 Sneakers For Men,₹499,70% off
92,aadi,Synthetic Leather Casual Partywear Wedding Sne...,₹298,62% off
93,Kavon,"Casual Loafers, Sneakers Shoes for Men Pack of...",₹370,62% off
94,Birde,489 Black Sneakers For Men,₹757,62% off
95,VORII,Sneakers For Men,₹379,78% off
96,"""trend""",Casual Sneaker Sneakers For Men,₹426,58% off
97,Kraasa,Sneakers For Men,₹416,43% off
98,Echor,Sneakers Sneakers For Men,₹569,50% off
99,Fzzirok,Men 5014 Latest Collection Stylish Casual Spor...,₹499,60% off

In [446]:
#Q9: Go to the link - https://www.myntra.com/shoes
#Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black”, as shown in the below image
#And then scrape First 100 shoes data you get

In [501]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.myntra.com/shoes"
driver.get(url)

In [502]:
filter_price=driver.find_element_by_xpath("//ul[@class='price-list']/li/label")
filter_price.click()

In [503]:
filter_color=driver.find_element_by_xpath("//span[@class='colour-label colour-colorDisplay']")
filter_color.click()
#<span data-colorhex="black" class="colour-label colour-colorDisplay" style="background-color: rgb(54, 69, 79);"></span>

In [504]:
import time
brand_list=[]
product_des_list=[]
price_list=[]

In [505]:
for i in range(0,4):
    for j in driver.find_elements_by_xpath("//h3[@class='product-brand']"):
        brand_list.append(j.text)
    for k in driver.find_elements_by_xpath("//h4[@class='product-product']"):
        product_des_list.append(k.text)
    for m in driver.find_elements_by_xpath("//span[@class='product-discountedPrice']"):
        price_list.append(m.text)
    driver.find_element_by_xpath("//li[@class='pagination-next']").click()
    time.sleep(2)

In [506]:
Product=pd.DataFrame()

Product["Brand"]=brand_list[:100]
Product["Description"]=product_des_list[:100]
Product["Price"]=price_list[:100]

In [507]:
Product

                      Brand                            Description     Price
0                  Red Tape                      Men Walking Shoes  Rs. 1224
1                   MENGLER                      Men Walking Shoes   Rs. 628
2            Reebok Classic                    Men Evader Sneakers  Rs. 3654
3                  Red Tape                      Men Walking Shoes  Rs. 1824
4                    ADIDAS             Men Shereton Running Shoes  Rs. 1949
5                Eego Italy                     Men Trekking Shoes   Rs. 899
6                  Red Tape                      Men Walking Shoes  Rs. 1224
7                  Provogue             Men Solid Horsebit Loafers   Rs. 799
8     HRX by Hrithik Roshan          Men Lite Run 1.0 Running shoe   Rs. 999
9                  AfroJack                      Men Walking Shoes   Rs. 655
10                   ADIDAS               Men Adicaz Running Shoes  Rs. 2339
11    HRX by Hrithik Roshan                      Men Running Shoes  Rs. 1259
12     Nabaiji By Decathlon             Unisex Aqua Aerobics Shoes   Rs. 959
13                 Roadster                         Men Flat Boots  Rs. 2914
14                 Skechers                     Women Sports Shoes  Rs. 3820
15                     Nike                     Men Training Shoes  Rs. 2096
16                    Crocs                   Women Open Toe Flats  Rs. 2624
17                     Puma                          Running Shoes  Rs. 3149
18          PUMA Motorsport         Ferrari Race Kart Cat Sneakers   Rs. 689
19                    ASICS         Pre Contend 4 Ps Running Shoes  Rs. 1749
20                 Red Tape                      Men Walking Shoes   Rs. 599
21                  Big Fox                      Men Running Shoes   Rs. 999
22              Crew STREET                      Men Running Shoes   Rs. 895
23                     Puma             Men Mirage OG Casual Shoes   Rs. 949
24               HIGHLANDER                           Men Sneakers   Rs. 996
25  Bond Street By Red Tape               Men Solid Formal Oxfords  Rs. 1649
26                    Sparx                      Men Running Shoes  Rs. 2469
27                 Red Tape                    Women Walking Shoes   Rs. 999
28         ADIDAS Originals           Men Easy VULC 2.0 Skateboard  Rs. 1539
29    HRX by Hrithik Roshan                   Men Street Run Shoes  Rs. 6115
..                      ...                                    ...       ...
70                       ID        Men Solid Leather Formal Derbys  Rs. 2274
71                    Yuuki                      Men Running Shoes  Rs. 2099
72                    Sparx                      Men Running Shoes   Rs. 734
73                  ZAPATOZ                     Women Heeled Boots  Rs. 2399
74                 AfroJack                      Men Running Shoes   Rs. 899
75           Reebok Classic                    Men Evader Sneakers  Rs. 1749
76                  El Paso          Men Textured Slip-On Sneakers   Rs. 798
77                     Puma         Men Trinity IDP Shoes Sneakers  Rs. 3846
78               DressBerry                            Women Pumps   Rs. 599
79              Sir Corbett                      Semi-Formal Shoes  Rs. 1979
80                     Puma                           Men Sneakers   Rs. 499
81         Mode by Red Tape                 Women Open Toe Sandals   Rs. 986
82                 Red Tape                      Men Walking Shoes   Rs. 719
83                 AfroJack      Men Slip-On Sneakers Casual Shoes  Rs. 1449
84                    Crocs                          Women Sandals   Rs. 679
85                   Champs                      Men Running Shoes  Rs. 4799
86    HRX by Hrithik Roshan                    Women Running Shoes  Rs. 2199
87                 Histeria                 Men Perforations Clogs  Rs. 6636
88                    Sparx                      Men Running Shoes  Rs. 4546
89                  El Paso                              Men Mules  Rs. 1139
90                 Red Tape                      Men Walking Shoes   Rs. 949
91                 Provogue  Men Knitted Upper Running Sport Shoes   Rs. 649
92                     Xtep                      Men Running Shoes  Rs. 4245
93                     Puma          Hybrid NX Ozone Running Shoes   Rs. 599
94                Red Chief          Leather High-Top Formal Shoes  Rs. 1359
95                     Puma                  Men Bent IDP Sneakers  Rs. 3996
96                     Nike             Women REACT ESCAPE Running  Rs. 1814
97                     Nike             Unisex Skateboarding Shoes   Rs. 659
98       Truffle Collection                   Women Open Toe Flats  Rs. 6115
99                    Sparx                      Men Running Shoes  Rs. 1499

[100 rows x 3 columns]

In [479]:
#Q10: Go to webpage https://www.amazon.in/
#Enter “Laptop” in the search field and then click the search icon.
#Then set CPU Type filter to “Intel Core i7” and “Intel Core i9”

In [552]:
driver=webdriver.Edge("msedgedriver.exe")
url= "https://www.amazon.in/"
driver.get(url)

In [553]:
user_inp=input("enter the product you want to search :")

enter the product you want to search :laptop

In [556]:
#finding element for job search bar
search_bar=driver.find_element_by_id("twotabsearchtextbox")      #locating search bar by id
                                           
search_bar.send_keys(user_inp)

In [557]:
search_button=driver.find_element_by_xpath("//div[@class='nav-search-submit nav-sprite']/span/input")             
search_button.click()

In [558]:
#driver.find_element_by_id("p_n_feature_thirteen_browse-bin/12598163031").click()            


CPU_selection1=driver.find_element_by_id("p_n_feature_thirteen_browse-bin/12598163031")             
CPU_selection1.click()